/**
 * Static content model.
 * @typedef {Object} Medication
 * @property {string} id
 * @property {string} name
 * @property {string} class
 * @property {boolean} [controlled]
 * @property {string} [schedule]
 * @property {string} mechanism
 * @property {string} commonUse
 * @property {string} dose
 * @property {string} onset
 * @property {string} duration
 * @property {string} sideEffects
 * @property {string} cautions
 * @property {string} pearl
 */

/** @type {Record<string, Medication>} */
window.PYXIS_MEDICATIONS = {
  // ── Induction ────────────────────────────────────────────────────────────
  propofol: {
    id: "propofol",
    name: "Propofol",
    class: "Intravenous general anesthetic",
    mechanism: "Positive modulation of the inhibitory function of the neurotransmitter GABA through ligand-gated GABA-A receptors.",
    commonUse: "Induction and maintenance of general anesthesia, MAC sedation, and ICU sedation.",
    dose: "Variable by use. Induction in adults: 2-2.5 mg/kg.Induction in elderly/debilitated: 1-1.5 mg/kg. Induction in pediatric patients (3-16 years): 2.5-3.5 mg/kg. Maintenance is titrated to patient's sedation levels (BIS) and vitals.",
    onset: "Anesthesia is induced within 40 seconds from the start of injection (one arm-brain circulation time), with blood-brain equilibration half-time of approximately 1-3 minutes.",
    duration: "Brief after bolus; context-sensitive half-time with infusion.",
    sideEffects: "Hypotension, apnea, pain on injection (lipid formulation). Often injected with lidocaine prior to reduce pain.",
    cautions: "Hemodynamic instability, egg/soy allergy (formulation-dependent), propofol infusion syndrome with prolonged high-dose infusion.",
    pearl: "While lidocaine pretreatment with venous occlusion is the gold standard for reducing propofol injection pain (reducing incidence by 71%), using an antecubital vein instead of a hand vein is actually the single most effective intervention, reducing pain incidence by 86%. (BMJ, Jalota et al, 2011).",
  },
  etomidate: {
    id: "etomidate",
    name: "Etomidate",
    class: "Imidazole sedative-hypnotic",
    mechanism: "Positive GABA-A receptor modulation.",
    commonUse: "Induction of general anesthesia, particularly in hemodynamically unstable patients. Used for Rapid Sequence Intubation (RSI).",
    dose: "0.3 mg/kg IV over 30-60 seconds (range 0.2-0.6 mg/kg); reduce dose in elderly/debilitated patients.",
    onset: "Within 1 minute (one arm-brain circulation time).",
    duration: "3-5 minutes after single induction dose.",
    sideEffects: "Myoclonus (involuntary muscle movements), pain on injection, postoperative nausea/vomiting, adrenal suppression lasting 6-8 hours (unresponsive to ACTH).",
    cautions: "Avoid in septic shock or critically ill pediatric patients due to adrenal suppression from 11β-hydroxylase inhibition (Circulation, Marino et al, 2018). Contraindicated in known hypersensitivity.",
    pearl: " The controversy around etomidate and mortality has been largely settled by recent evidence. While etomidate does cause adrenal suppression for up to 72 hours after a single dose, the 2025 NEJM multicenter trial (Casey et al) showed no difference in mortality compared to ketamine in critically ill adults undergoing intubation.",
  },
  ketamine: {
    id: "ketamine",
    name: "Ketamine",
    class: "Dissociative anesthetic",
    controlled: true,
    schedule: "DEA Schedule III",
    mechanism: "NMDA receptor antagonist; complex effects on multiple systems.",
    commonUse: "Induction, analgesia, asthma/bronchospasm, procedural sedation.",
    dose: "Induction ~1–2 mg/kg IV; analgesic smaller doses per context.",
    onset: "Rapid IV.",
    duration: "Dose-dependent; emergence phenomena possible.",
    sideEffects: "Hypertension/tachycardia, emergence reactions, increased secretions.",
    cautions: "Active CAD or severe uncontrolled HTN may be relative concerns; ICP/eye injury contexts require judgment.",
    pearl: "Bronchodilation and preserved reflexes can be advantages — still protect airway and monitor hemodynamics.",
  },
  midazolam: {
    id: "midazolam",
    name: "Midazolam",
    class: "Benzodiazepine",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "GABA-A potentiation.",
    commonUse: "Anxiolysis, amnesia, sedation, adjunct to induction.",
    dose: "Highly context-dependent; small incremental IV doses in adults.",
    onset: "Rapid IV.",
    duration: "Intermediate; prolonged in elderly/renal/hepatic impairment.",
    sideEffects: "Respiratory depression, oversedation, paradoxical agitation (rare).",
    cautions: "Combine carefully with opioids; flumazenil available but use with caution.",
    pearl: "In frail adults, go slow — the learning point is pharmacodynamic sensitivity, not a single cookbook number.",
  },
  // ── Paralytics ────────────────────────────────────────────────────────────
  rocuronium: {
    id: "rocuronium",
    name: "Rocuronium",
    class: "Non-depolarizing NMB",
    mechanism: "Competitive antagonism at nicotinic acetylcholine receptors.",
    commonUse: "Intubation and neuromuscular block for surgery.",
    dose: "Intubating dose commonly ~0.6–1.2 mg/kg IV depending on timing.",
    onset: "Faster at higher doses; sugammadex enables rapid reversal.",
    duration: "Moderate; variable with metabolism and redosing.",
    sideEffects: "Residual weakness if inadequately reversed; histamine release uncommon at clinical doses.",
    cautions: "Confirm ventilation and reversal plan; allergy to sugammadex is a separate consideration.",
    pearl: "Pair rocuronium with a clear plan for airway and reversal — sugammadex vs neostigmine is a patient-factor decision.",
  },
  succinylcholine: {
    id: "succinylcholine",
    name: "Succinylcholine",
    class: "Depolarizing NMB",
    mechanism: "Persistent depolarization at motor endplate.",
    commonUse: "Rapid sequence intubation when not contraindicated.",
    dose: "Commonly ~1–1.5 mg/kg IV for RSI.",
    onset: "Very rapid.",
    duration: "Short (minutes) in typical metabolism.",
    sideEffects: "Bradycardia (especially repeat dosing in children), hyperkalemia risk, myalgia, masseter spasm.",
    cautions: "Hyperkalemia risk in burns, denervation, crush injury, prolonged immobility; malignant hyperthermia trigger.",
    pearl: "Fast on/fast off is the trade — always screen for hyperkalemia and MH risk before reaching for it.",
  },
  // ── Pressors ─────────────────────────────────────────────────────────────
  phenylephrine: {
    id: "phenylephrine",
    name: "Phenylephrine",
    class: "Alpha-1 agonist",
    mechanism: "Vasoconstriction with minimal direct beta activity at clinical doses.",
    commonUse: "Treat hypotension, especially vasodilated states.",
    dose: "Bolus dosing common in OR; infusion per protocol and response.",
    onset: "Rapid.",
    duration: "Short bolus effect; infusion titration.",
    sideEffects: "Reflex bradycardia, hypertension if excess.",
    cautions: "Severe uncontrolled hypertension, some tachyarrhythmia contexts.",
    pearl: "Watch HR — reflex bradycardia can be the limiting factor in a vasodilated patient.",
  },
  ephedrine: {
    id: "ephedrine",
    name: "Ephedrine",
    class: "Indirect sympathomimetic",
    mechanism: "Releases norepinephrine; mixed alpha/beta effects.",
    commonUse: "Hypotension, especially spinal/epidural sympathectomy.",
    dose: "Common small bolus titration (e.g., 5–10 mg IV) per response.",
    onset: "Moderately rapid.",
    duration: "Longer than phenylephrine bolus; tachyphylaxis with repeated dosing.",
    sideEffects: "Tachycardia, hypertension.",
    cautions: "Tachyarrhythmias, severe coronary disease — clinical judgment.",
    pearl: "Ephedrine raises HR more than phenylephrine often does — choose based on whether you want HR up or down.",
  },
  norepinephrine: {
    id: "norepinephrine",
    name: "Norepinephrine",
    class: "Catecholamine vasopressor",
    mechanism: "Alpha > beta-1 agonism at typical infusion doses.",
    commonUse: "Vasodilatory shock, refractory hypotension.",
    dose: "Infusion titrated to perfusion and institutional protocol.",
    onset: "Rapid when IV.",
    duration: "Infusion-dependent.",
    sideEffects: "Ischemia if excessive vasoconstriction, arrhythmias.",
    cautions: "Extravasation risk; central line preferred for prolonged high doses.",
    pearl: "First-line vasopressor in many shock algorithms — still treat the cause.",
  },
  vasopressin: {
    id: "vasopressin",
    name: "Vasopressin",
    class: "Vasopressor (non-catecholamine)",
    mechanism: "V1 receptor-mediated vasoconstriction.",
    commonUse: "Adjunct in vasodilatory shock.",
    dose: "Low-dose infusion per protocol.",
    onset: "Gradual compared with bolus catecholamines.",
    duration: "Context of infusion.",
    sideEffects: "Ischemia, hyponatremia with prolonged use.",
    cautions: "Refractory shock as team-based decision; monitor perfusion.",
    pearl: "Use as an adjunct highlights that shock is often multifactorial — catecholamine-sparing strategy can help selected patients.",
  },
  // ── Reversal / rescue ─────────────────────────────────────────────────────
  sugammadex: {
    id: "sugammadex",
    name: "Sugammadex",
    class: "Selective relaxant binding agent",
    mechanism: "Encapsulates steroidal NMBDs (rocuronium/vecuronium).",
    commonUse: "Rapid reversal of rocuronium/vecuronium-induced block.",
    dose: "Depends on depth of block and agent — institutional tables.",
    onset: "Rapid reversal when dosed appropriately.",
    duration: "Reversal event; re-paralysis possible if competitive factors change.",
    sideEffects: "Hypersensitivity (rare but important), bradycardia reported.",
    cautions: "Allergy history; ensure adequate respiratory support until confirmed recovery.",
    pearl: "Train of four and clinical strength assessment still matter — technology doesn't replace bedside judgment.",
  },
  neostigmine: {
    id: "neostigmine",
    name: "Neostigmine",
    class: "Acetylcholinesterase inhibitor",
    mechanism: "Increases acetylcholine at synapse.",
    commonUse: "Reversal of non-depolarizing NMB with appropriate TOF.",
    dose: "Weight-based with glycopyrrolate or atropine pairing per protocol.",
    onset: "Several minutes; slower than sugammadex.",
    duration: "Watch for recurarization if given at inadequate depth of recovery.",
    sideEffects: "Bradycardia (mitigated by anticholinergic), salivation, nausea.",
    cautions: "Avoid reversing deep block; airway complications if rushed.",
    pearl: "Reversal is safest when block is already fading — confirm with quantitative neuromuscular monitoring when available.",
  },
  glycopyrrolate: {
    id: "glycopyrrolate",
    name: "Glycopyrrolate",
    class: "Anticholinergic",
    mechanism: "Competitive muscarinic antagonist.",
    commonUse: "Often paired with neostigmine; reduces secretions.",
    dose: "Paired ratio with neostigmine per institutional guideline.",
    onset: "IV onset minutes.",
    duration: "Longer than atropine in many comparisons.",
    sideEffects: "Tachycardia, dry mouth, urinary retention.",
    cautions: "Tachyarrhythmias, narrow-angle glaucoma considerations.",
    pearl: "Think autonomic balance — you're reversing neuromuscular block without letting vagal tone swing the patient.",
  },
  naloxone: {
    id: "naloxone",
    name: "Naloxone",
    class: "Opioid antagonist",
    mechanism: "Mu-opioid competitive antagonism.",
    commonUse: "Opioid-induced respiratory depression or overdose.",
    dose: "Titrate small boluses in perioperative settings to restore ventilation without eliminating analgesia.",
    onset: "Rapid IV.",
    duration: "May be shorter than long-acting opioids — re-sedation possible.",
    sideEffects: "Acute pain, hypertension, pulmonary edema (rare).",
    cautions: "Severe unmasking of pain/catecholamine surge; use monitored titration.",
    pearl: "In the OR, often titrate to respiratory drive rather than 'fully awake' — unless overdose is the problem.",
  },
  flumazenil: {
    id: "flumazenil",
    name: "Flumazenil",
    class: "Benzodiazepine antagonist",
    mechanism: "Competitive antagonism at benzodiazepine site.",
    commonUse: "Benzodiazepine oversedation (selected contexts).",
    dose: "Small incremental IV doses; duration may require redosing.",
    onset: "Rapid.",
    duration: "Shorter than many benzodiazepines — re-sedation risk.",
    sideEffects: "Seizure risk in chronic benzodiazepine dependence or mixed overdoses.",
    cautions: "Mixed ingestions (TCAs, etc.) — consult toxicology when appropriate.",
    pearl: "Rescue reversal is not a substitute for airway support and monitoring.",
  },
  // ── Supportive ────────────────────────────────────────────────────────────
  lidocaine: {
    id: "lidocaine",
    name: "Lidocaine",
    class: "Amide local anesthetic / antiarrhythmic",
    mechanism: "Sodium channel blockade.",
    commonUse: "Local infiltration, IV adjuncts, ventricular arrhythmias.",
    dose: "Highly indication-specific; watch cumulative IV dose.",
    onset: "Rapid for IV/local.",
    duration: "Short to intermediate.",
    sideEffects: "CNS toxicity at high levels, hypotension, bradycardia in toxicity.",
    cautions: "Max dose limits, severe heart block without pacing capability.",
    pearl: "In anesthesia, know your indication — local infiltration dosing is not the same mental model as antiarrhythmic boluses.",
  },
  ondansetron: {
    id: "ondansetron",
    name: "Ondansetron",
    class: "5-HT3 antagonist",
    mechanism: "Blocks serotonin receptors relevant to nausea pathways.",
    commonUse: "PONV prophylaxis and treatment.",
    dose: "Common IV doses per guideline; QT considerations at higher cumulative exposure.",
    onset: "Minutes IV.",
    duration: "Several hours.",
    sideEffects: "Headache, constipation, QT prolongation (dose/context).",
    cautions: "Congenital long QT, electrolyte abnormalities — team risk/benefit.",
    pearl: "Multimodal PONV prophylaxis beats stacking the same class repeatedly.",
  },
  dexamethasone: {
    id: "dexamethasone",
    name: "Dexamethasone",
    class: "Corticosteroid",
    mechanism: "Broad anti-inflammatory and immunologic effects.",
    commonUse: "PONV prophylaxis, airway edema concerns, antiemetic adjunct.",
    dose: "Low IV doses common for PONV; higher for some indications.",
    onset: "Onset over time depending on effect measured.",
    duration: "Long relative to many perioperative drugs.",
    sideEffects: "Hyperglycemia, mood effects, infection concern at higher/chronic exposure.",
    cautions: "Uncontrolled hyperglycemia; perioperative steroid plans in chronic steroid patients.",
    pearl: "For PONV, it's often part of a bundle — not a magic bullet alone.",
  },
  atropine: {
    id: "atropine",
    name: "Atropine",
    class: "Anticholinergic",
    mechanism: "Muscarinic antagonist.",
    commonUse: "Bradycardia treatment; sometimes with neostigmine reversal.",
    dose: "Bradycardia dosing per ACLS/institution.",
    onset: "Rapid IV.",
    duration: "Variable.",
    sideEffects: "Tachycardia, dry mouth, urinary retention, delirium in sensitive patients.",
    cautions: "Narrow-angle glaucoma, tachyarrhythmias.",
    pearl: "Treat symptomatic bradycardia and the cause — depth, vagal stimulus, drugs, ischemia.",
  },
  // ── Controlled substances (in the locked grid) ───────────────────────────
  fentanyl: {
    id: "fentanyl",
    name: "Fentanyl",
    class: "Opioid — synthetic phenylpiperidine",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Intraoperative analgesia, induction adjunct, sedation.",
    dose: "Titrated in small IV boluses intraoperatively; context-sensitive half-time increases with infusion duration.",
    onset: "Rapid IV.",
    duration: "Short to intermediate; redistribution-dependent.",
    sideEffects: "Respiratory depression, chest wall rigidity (rapid large bolus), bradycardia, nausea.",
    cautions: "Avoid rapid large boluses; rigidity can impair ventilation. Tolerance and dependence with repeated use.",
    pearl: "High lipophilicity means context-sensitive half-time matters — a 'short-acting' drug becomes long-acting with prolonged infusion.",
  },
  hydromorphone: {
    id: "hydromorphone",
    name: "Hydromorphone (Dilaudid)",
    class: "Opioid — semisynthetic",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; ~5× more potent than morphine per mg.",
    commonUse: "Moderate-to-severe pain; PACU and postoperative analgesia.",
    dose: "~5× more potent than morphine by weight — careful conversion. IV bolus titration per response.",
    onset: "Rapid IV.",
    duration: "Shorter than morphine.",
    sideEffects: "Respiratory depression, nausea, hypotension, sedation.",
    cautions: "Conversion errors are a significant safety risk — verify equianalgesic dose when switching opioids.",
    pearl: "Potency difference from morphine is a common source of medication errors during transitions of care.",
  },
  morphine: {
    id: "morphine",
    name: "Morphine",
    class: "Opioid — natural alkaloid",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; reference standard for equianalgesic conversions.",
    commonUse: "Moderate-to-severe pain; sometimes used intraoperatively.",
    dose: "Reference standard for opioid equianalgesic conversions.",
    onset: "Slower IV onset than fentanyl.",
    duration: "Longer than fentanyl; active metabolite (M6G) accumulates in renal impairment.",
    sideEffects: "Histamine release (hypotension, pruritus), respiratory depression, nausea.",
    cautions: "Renal impairment increases active metabolite accumulation; histamine release can be hemodynamically relevant.",
    pearl: "Morphine is the equianalgesic reference — knowing it helps you convert between opioids safely.",
  },
  lorazepam: {
    id: "lorazepam",
    name: "Lorazepam (Ativan)",
    class: "Benzodiazepine",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "GABA-A potentiation.",
    commonUse: "Procedural sedation, alcohol withdrawal, seizure management.",
    dose: "Context-dependent; IV dosing titrated per indication.",
    onset: "Moderate IV onset.",
    duration: "Longer than midazolam.",
    sideEffects: "Respiratory depression, oversedation, propylene glycol toxicity with high-dose IV infusion.",
    cautions: "Propylene glycol vehicle in IV formulation — monitor with prolonged infusions.",
    pearl: "Longer duration than midazolam means it's often preferred for alcohol withdrawal but can overshoot for brief procedural sedation.",
  },
  meperidine: {
    id: "meperidine",
    name: "Meperidine (Demerol)",
    class: "Opioid — synthetic",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; also anticholinergic and local anesthetic properties.",
    commonUse: "Low-dose treatment of postoperative shivering. Rarely used as primary analgesic due to toxicity.",
    dose: "Low doses (12.5–25 mg IV) for shivering. Avoid repeated/high dosing.",
    onset: "Moderate IV.",
    duration: "Intermediate.",
    sideEffects: "Normeperidine accumulation (seizures, dysphoria), serotonin syndrome risk with MAOIs.",
    cautions: "Toxic metabolite accumulates with renal impairment — avoid as a general analgesic.",
    pearl: "The shivering indication is legitimate and dose-limited; avoid where better options exist.",
  },
  remifentanil: {
    id: "remifentanil",
    name: "Remifentanil (Ultiva)",
    class: "Opioid — synthetic fentanyl derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Intraoperative analgesia, induction adjunct, sedation.",
    dose: "Titrated in small IV boluses intraoperatively; context-sensitive half-time increases with infusion duration.",
    onset: "Rapid IV.",
    duration: "Short to intermediate; redistribution-dependent.",
    sideEffects: "Respiratory depression, chest wall rigidity (rapid large bolus), bradycardia, nausea.",
    cautions: "Avoid rapid large boluses; rigidity can impair ventilation. Tolerance and dependence with repeated use.",
    pearl: "High lipophilicity means context-sensitive half-time matters — a 'short-acting' drug becomes long-acting with prolonged infusion.",
  },
  sufentanil: {
    id: "sufentanil",
    name: "Sufentanil",
    class: "Opioid — synthetic fentanyl derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Intraoperative analgesia, induction adjunct, sedation.",
    dose: "Titrated in small IV boluses intraoperatively; context-sensitive half-time increases with infusion duration.",
    onset: "Rapid IV.",
  },
  methadone: {
    id: "methadone",
    name: "Methadone",
    class: "Opioid — synthetic",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Intraoperative analgesia, induction adjunct, sedation.",
    dose: "Titrated in small IV boluses intraoperatively; context-sensitive half-time increases with infusion duration.",
    onset: "Rapid IV.",
    duration: "Short to intermediate; redistribution-dependent.",
    sideEffects: "Respiratory depression, chest wall rigidity (rapid large bolus), bradycardia, nausea.",
    cautions: "Avoid rapid large boluses; rigidity can impair ventilation. Tolerance and dependence with repeated use.",
    pearl: "High lipophilicity means context-sensitive half-time matters — a 'short-acting' drug becomes long-acting with prolonged infusion.",
  },
  diazepam: {
    id: "diazepam",
    name: "Diazepam",
    class: "Benzodiazepine",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "GABA-A potentiation.",
    commonUse: "Procedural sedation, alcohol withdrawal, seizure management.",
    dose: "Context-dependent; IV dosing titrated per indication.",
    onset: "Moderate IV onset.",
    duration: "Longer than midazolam.",
    sideEffects: "Respiratory depression, oversedation, propylene glycol toxicity with high-dose IV infusion.",
    cautions: "Propylene glycol vehicle in IV formulation — monitor with prolonged infusions.",
    pearl: "Longer duration than midazolam means it's often preferred for alcohol withdrawal but can overshoot for brief procedural sedation.",
  },
  oxycodone: {
    id: "oxycodone",
    name: "Oxycodone",
    class: "Opioid — synthetic",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Moderate-to-severe pain; sometimes used intraoperatively.",
    dose: "Reference standard for opioid equianalgesic conversions.",
    onset: "Slower IV onset than fentanyl.",
    duration: "Longer than fentanyl; active metabolite (M6G) accumulates in renal impairment.",
    sideEffects: "Histamine release (hypotension, pruritus), respiratory depression, nausea.",
    cautions: "Renal impairment increases active metabolite accumulation; histamine release can be hemodynamically relevant.",
    pearl: "Morphine is the equianalgesic reference — knowing it helps you convert between opioids safely.",
  },
  tramadol: {
    id: "tramadol",
    name: "Tramadol",
    class: "Opioid — synthetic",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Moderate-to-severe pain; sometimes used intraoperatively.",
    dose: "Reference standard for opioid equianalgesic conversions.",
    onset: "Slower IV onset than fentanyl.",
    duration: "Longer than fentanyl; active metabolite (M6G) accumulates in renal impairment.",
    sideEffects: "Histamine release (hypotension, pruritus), respiratory depression, nausea.",
    cautions: "Renal impairment increases active metabolite accumulation; histamine release can be hemodynamically relevant.",
    pearl: "Morphine is the equianalgesic reference — knowing it helps you convert between opioids safely.",
  },
  codeine: {
    id: "codeine",
    name: "Codeine",
    class: "Opioid — natural alkaloid",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Moderate-to-severe pain; sometimes used intraoperatively.",
    dose: "Reference standard for opioid equianalgesic conversions.",
    onset: "Slower IV onset than fentanyl.",
    duration: "Longer than fentanyl; active metabolite (M6G) accumulates in renal impairment.",
    sideEffects: "Histamine release (hypotension, pruritus), respiratory depression, nausea.",
    cautions: "Renal impairment increases active metabolite accumulation; histamine release can be hemodynamically relevant.",
    pearl: "Morphine is the equianalgesic reference — knowing it helps you convert between opioids safely.",
  },
  buprenorphine: {
    id: "buprenorphine",
    name: "Buprenorphine",
    class: "Opioid — synthetic",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic.",
    commonUse: "Moderate-to-severe pain; sometimes used intraoperatively.",
    dose: "Reference standard for opioid equianalgesic conversions.",
    onset: "Slower IV onset than fentanyl.",
    duration: "Longer than fentanyl; active metabolite (M6G) accumulates in renal impairment.",
    sideEffects: "Histamine release (hypotension, pruritus), respiratory depression, nausea.",
    cautions: "Renal impairment increases active metabolite accumulation; histamine release can be hemodynamically relevant.",
    pearl: "Morphine is the equianalgesic reference — knowing it helps you convert between opioids safely.",
  },
};

/** Supply bin taxonomy (10 items, 2 rows × 5 columns) */
window.PYXIS_SUPPLY_BINS = [
  // Row 1
  { id: "tube-caps",     label: "Tube caps",    row: 1, description: "Red and green tube caps for IV ports and stopcocks. Red = no additive (blood draws), Green = heparinized flush. Know your institution's color coding." },
  { id: "tourniquets",   label: "Tourniquets",  row: 1, description: "Used for IV placement — tighten proximal to intended IV site to engorge veins. Release as soon as flashback is seen." },
  { id: "alcohol-wipes", label: "Alcohol wipes", row: 1, description: "70% isopropyl pads for IV site prep, needle prep, and general antisepsis. Allow to dry before insertion for best effect." },
  { id: "gauze",         label: "Gauze",         row: 1, description: "4×4 gauze pads — field prep, bleeding control, airway work, and general OR use." },
  { id: "tape",          label: "Tape",          row: 1, description: "Multiple types: silk tape for ETT securing, paper tape for wound wrapping, clear Tegaderm-style for A-lines and IVs. Know which tape for which use." },
  // Row 2
  { id: "ecg-stickers",  label: "ECG stickers",  row: 2, description: "5-lead ECG electrode pads (RA, LA, RL, LL, V lead). Check lead contact and skin prep before draping; poor contact = artifact, poor diagnosis." },
  { id: "oral-airways",  label: "Oral airways",  row: 2, description: "OPAs (Guedel) for maintaining airway in unconscious patients. Size by measuring corner of mouth to earlobe. Do not use in conscious patients — triggers gag reflex." },
  { id: "lab-tubes",     label: "Lab tubes",     row: 2, description: "Blood collection tubes: purple top (EDTA → CBC), green top (lithium heparin → BMP), blue top (citrate → coag/PT/INR), gold top (serum separator → type & screen)." },
  { id: "tegaderms",     label: "Tegaderms",     row: 2, description: "Transparent polyurethane film dressing — standard for securing peripheral IVs and central line sites while maintaining visualization of the insertion site." },
  { id: "nasal-supplies", label: "Nasal / oral adj.", row: 2, description: "Nasal cannulas (2–6 L/min O2), nasal trumpets (lubricate well; relative contraindication in suspected basilar skull fracture), tongue depressors. Know what you're reaching for." },
];

/** Main drug drawer taxonomy */
window.PYXIS_DRAWERS = [
  { id: "induction",   label: "Induction",                    shortLabel: "Induction",   medicationIds: ["propofol", "etomidate", "ketamine", "midazolam"] },
  { id: "paralytics",  label: "Paralytics",                   shortLabel: "Paralytics",  medicationIds: ["rocuronium", "succinylcholine"] },
  { id: "pressors",    label: "Pressors / hemodynamic",       shortLabel: "Pressors",    medicationIds: ["phenylephrine", "ephedrine", "norepinephrine", "vasopressin"] },
  { id: "reversal",    label: "Reversal / rescue",            shortLabel: "Reversal",    medicationIds: ["sugammadex", "neostigmine", "glycopyrrolate", "naloxone", "flumazenil"] },
  { id: "supportive",  label: "Supportive / airway-adjacent", shortLabel: "Supportive",  medicationIds: ["lidocaine", "ondansetron", "dexamethasone", "atropine"] },
];

/**
 * Controlled-substance cell mapping (15 cells, 3 rows × 5 cols).
 * null = empty/locked slot.
 */
window.PYXIS_CONTROLLED_CELLS = [
  "fentanyl",     "remifentanil", "hydromorphone", "oxycodone",     "morphine",
  "methadone",    "sufentanil",   "midazolam",     "lorazepam",     "diazepam",
  "tramadol",      "codeine",     "buprenorphine", "meperidine",    "ketamine",
];

/** Left-cabinet specialty drawers */
window.PYXIS_LEFT_DRAWERS = [
  {
    id: "airway",
    label: "Airway",
    shortLabel: "Airway",
    items: [
      { id: "mac-blade",   name: "MAC Blade",           category: "Laryngoscopy",           description: "Curved Macintosh blade — tip goes in the vallecula (anterior to epiglottis). Common sizes: MAC 3 (average adult), MAC 4 (large adult). Technique: lift the handle forward-upward, never lever on the teeth." },
      { id: "ett",         name: "Endotracheal Tube",   category: "Intubation",             description: "Cuffed tubes for a definitive airway. Adults: 7.0–7.5 ID for females, 7.5–8.0 ID for males. Confirm position: bilateral breath sounds, ETCO₂ waveform, symmetric chest rise, CXR." },
      { id: "lma",         name: "LMA",                 category: "Supraglottic airway",    description: "Laryngeal Mask Airway — sits in the hypopharynx over the laryngeal inlet. Does NOT protect against aspiration. Classic, ProSeal, i-gel variants available. Size by patient weight." },
      { id: "glidescope",  name: "GlideScope",          category: "Video laryngoscopy",     description: "Video laryngoscope with a 60° blade curve. Provides indirect view without direct line-of-sight. Use with a malleable stylet shaped to the blade curve. Particularly helpful in anticipated difficult airways." },
      { id: "bougie",      name: "Bougie",              category: "Difficult airway adjunct", description: "Tracheal introducer — used when you can visualize the epiglottis but not the cords. Insert under epiglottis, feel 'tracheal clicks', thread ETT over bougie. Essential rescue tool in unexpected difficult airways." },
      { id: "bag-mask",    name: "Bag-Valve Mask",      category: "Emergency ventilation",  description: "BVM for manual ventilation — preoxygenation, rescue BMV during failed intubation, or patient transport. EC-clamp grip for 1-person mask seal. 2-person technique (one seals, one squeezes) if significant leak." },
    ],
  },
  {
    id: "lines",
    label: "Lines & Infusion",
    shortLabel: "Lines",
    items: [
      { id: "peripheral-iv",  name: "Peripheral IV (PIV)",       category: "Vascular access",      description: "Angiocath in a peripheral vein. Gauge guide: 14G (trauma/massive transfusion), 16–18G (standard OR), 20–22G (routine/peds). Larger bore = faster flow (Poiseuille's law: flow ∝ r⁴). Antecubital and forearm veins preferred." },
      { id: "a-line",         name: "Arterial Line (A-line)",    category: "Invasive monitoring",  description: "Intra-arterial catheter (usually radial) for beat-to-beat BP monitoring and arterial blood gas access. Modified Allen test assesses collateral flow before insertion. Flush system with pressurized heparinized saline (300 mmHg bag)." },
      { id: "cvc",            name: "Central Venous Catheter",   category: "Central access",       description: "Placed in internal jugular, subclavian, or femoral vein. Indications: CVP monitoring, drug infusion, access when peripheral unavailable. Seldinger technique (wire → dilator → catheter). Confirm with CXR post-insertion." },
      { id: "infusion-lines", name: "Infusion Pump Tubing",      category: "IV tubing",            description: "Macrobore tubing for high-flow resuscitation. Microbore for TIVA, vasopressors, and precision delivery. Components: spike (bag piercing), drip chamber (flow visualization), roller clamp (manual flow control), Y-sites (medication injection), luer-lock connectors, and pump cassette segment." },
      { id: "fluid-bags",     name: "Fluid Bags (NS / LR)",      category: "IV fluids",            description: "Normal Saline (0.9% NaCl): isotonic, compatible with blood products, but risks hyperchloremic metabolic acidosis with large volumes. Lactated Ringers: more physiologic electrolyte balance, preferred for surgical resuscitation in many institutions." },
      { id: "infusion-pump",  name: "Infusion Pump",             category: "Equipment",            description: "Programmable pump for precise delivery of vasopressors (e.g., norepinephrine), TIVA agents (e.g., propofol, remifentanil), and antibiotics. Always set rate (mL/hr) and volume to be infused (VTBI). Know your unit's air-in-line and occlusion alarm behaviors." },
    ],
  },
];

/** Attendings for About Us page */
window.ABOUT_RESIDENTS = [
  {
    id: "resident-1",
    name: "Dr. Justin Anzalone",
    initials: "JA",
    color: "#207a5e",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/justinanzalone.jpg",
    bio: "Originally from Louisiana, Dr. Anzalone completed his undergraduate degree at the University of Louisiana at Lafayette. He continued on the complete a masters of physician assistant studies at New York Institute of Technology, where he practiced for 8 years prior to returning to complete his medical school training at Ross University School of Medicine. Dr. Anzalone and his wife, Yvette, have three beautiful daughters: Alexandra, Caroline, and Annalise. Dr. Anzalone enjoys spending time with family, hiking, gravel cycling, roasting coffee, and traveling.",
    email: "justin.anzalone@yale.edu"
  },
  {
    id: "resident-2",
    name: "Dr. Aiden Rossi",
    initials: "AR",
    color: "#1a7a8a",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/dr-rossi.jpg",
    bio: "Dr. Rossi is a CA-2 resident with a strong interest in cardiac and thoracic anesthesia. He completed his intern year in general surgery and has been recognized for his teaching of medical students on the anesthesia clerkship. He attended Tufts University School of Medicine.",
    email: "aiden.rossi@yale.edu"
  },
  {
    id: "resident-3",
    name: "Dr. Sofia Reyes",
    initials: "SR",
    color: "#8a5a1a",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/dr-reyes.jpg",
    bio: "Dr. Reyes has a particular interest in obstetric anesthesia and global health. She has participated in medical mission trips to expand access to safe surgical care. She graduated from the University of Michigan Medical School and completed her internship at Yale-New Haven Hospital.",
    email: "sofia.reyes@yale.edu"
  },
  {
    id: "resident-4",
    name: "Dr. Marcus Kim",
    initials: "MK",
    color: "#4a6b1a",
    title: "CA-3 Resident (PGY-4)",
    photo: "images/dr-kim.jpg",
    bio: "Dr. Kim is a senior resident in his final clinical anesthesia year. He has served as a chief resident and plans to pursue a fellowship in critical care medicine. He is especially interested in the pharmacology of induction agents and the neuroscience of consciousness during anesthesia.",
    email: "marcus.kim@yale.edu"
  },
];

window.ABOUT_ATTENDINGS = [
  {
    id: "attending-1",
    name: "Dr. Chris Szabo",
    initials: "CS",
    color: "#286dc0",
    title: "Associate Professor of Anesthesiology",
    photo: "images/christopherszabo_thumb.jpg",
    photo_high: "images/christopherszabo_high.jpg",
    bio: "Dr. Christopher Szabo is Associate Professor of Anesthesiology at Yale New Haven Hospital. He received his medical degree from the University of Connecticut School of Medicine in 2008. Following his Anesthesia residency at Yale University, Dr. Szabo went on to complete both a Critical Care fellowship and a Postdoctoral Fellowship at Columbia University. In 2017, Dr. Szabo joined the Yale University School of Medicine faculty, providing clinical care to patients in the General Section, Cardiothoracic ICU. Dr. Szabo first conceptualized the interactive anesthesia OR guide based on J.K. Rowling's old websites.",
    email: "christopher.szabo@yale.edu"
  },
  {
    id: "attending-2",
    name: "Dr. John Guzzi",
    initials: "JG",
    color: "#1a6655",
    title: "Assistant Professor of Anesthesiology",
    photo: "images/johnguzzi_thumb.jpg",
    photo_high: "images/johnguzzi_high.jpg",
    bio: "Dr. John Guzzi is an Assistant Professor of Anesthesiology at Yale. He is also the Rotation Director for the Advanced Training Period (ATP) Subinternship and Clerkship Site Director for York Street Campus.",
    email: "john.guzzi@yale.edu"
  },
];
