/**
 * Static content model.
 * @typedef {Object} Medication
 * @property {string} id
 * @property {string} name
 * @property {string} class
 * @property {boolean} [controlled]
 * @property {string} [schedule]
 * @property {string} mechanism
 * @property {string} commonUse
 * @property {string} dose
 * @property {string} onset
 * @property {string} duration
 * @property {string} sideEffects
 * @property {string} cautions
 * @property {string} pearl
 */

/** @type {Record<string, Medication>} */
window.PYXIS_MEDICATIONS = {
  // ── Induction ────────────────────────────────────────────────────────────
  propofol: {
    id: "propofol",
    name: "Propofol",
    class: "Intravenous general anesthetic",
    mechanism: "Positive modulation of the inhibitory function of the neurotransmitter GABA through ligand-gated GABA-A receptors.",
    commonUse: "Induction and maintenance of general anesthesia, MAC sedation, and ICU sedation.",
    dose: "Variable by use. Induction in adults: 2-2.5 mg/kg.Induction in elderly/debilitated: 1-1.5 mg/kg. Induction in pediatric patients (3-16 years): 2.5-3.5 mg/kg. Maintenance is titrated to patient's sedation levels (BIS) and vitals.",
    onset: "Anesthesia is induced within 40 seconds from the start of injection (one arm-brain circulation time), with blood-brain equilibration half-time of approximately 1-3 minutes.",
    duration: "Brief after bolus; context-sensitive half-time with infusion.",
    sideEffects: "Hypotension, apnea, pain on injection (lipid formulation). Often injected with lidocaine prior to reduce pain.",
    cautions: "Hemodynamic instability, egg/soy allergy (formulation-dependent), propofol infusion syndrome with prolonged high-dose infusion.",
    pearl: "While lidocaine pretreatment with venous occlusion is the gold standard for reducing propofol injection pain (reducing incidence by 71%), using an antecubital vein instead of a hand vein is actually the single most effective intervention, reducing pain incidence by 86%. (BMJ, Jalota et al, 2011).",
  },
  etomidate: {
    id: "etomidate",
    name: "Etomidate",
    class: "Imidazole sedative-hypnotic",
    mechanism: "Positive GABA-A receptor modulation.",
    commonUse: "Induction of general anesthesia, particularly in hemodynamically unstable patients. Used for Rapid Sequence Intubation (RSI).",
    dose: "0.3 mg/kg IV over 30-60 seconds (range 0.2-0.6 mg/kg); reduce dose in elderly/debilitated patients.",
    onset: "Within 1 minute (one arm-brain circulation time).",
    duration: "3-5 minutes after single induction dose.",
    sideEffects: "Myoclonus (involuntary muscle movements), pain on injection, postoperative nausea/vomiting, adrenal suppression lasting 6-8 hours (unresponsive to ACTH).",
    cautions: "Avoid in septic shock or critically ill pediatric patients due to adrenal suppression from 11β-hydroxylase inhibition (Circulation, Marino et al, 2018). Contraindicated in known hypersensitivity.",
    pearl: " The controversy around etomidate and mortality has been largely settled by recent evidence. While etomidate does cause adrenal suppression for up to 72 hours after a single dose, the 2025 NEJM multicenter trial (Casey et al) showed no difference in mortality compared to ketamine in critically ill adults undergoing intubation.",
  },
  ketamine: {
    id: "ketamine",
    name: "Ketamine",
    class: "Dissociative anesthetic",
    controlled: true,
    schedule: "DEA Schedule III",
    mechanism: "Non-competitive antagonist of the NMDA (N-methyl-D-aspartate) receptor; produces dissociative anesthesia and indirect sympathomimetic effects via inhibition of catecholamine reuptake.",
    commonUse: "Induction of general anesthesia, particularly in hemodynamically unstable patients, trauma, and patients with reactive airway disease; also used for procedural sedation.",
    dose: "IV induction: 1-2 mg/kg (average 2 mg/kg produces 5-10 minutes of anesthesia). Other uses variable.",
    onset: "IV: 30 seconds; IM: 3-4 minutes.",
    duration: "IV: 5-10 minutes; IM: 12-25 minutes.",
    sideEffects: "Emergence reactions (hallucinations, vivid dreams, delirium), nystagmus, increased salivation, nausea/vomiting, transient hypertension and tachycardia, elevated intracranial/intraocular pressure, laryngospasm (rare), hepatotoxicity with chronic use, genitourinary pain with chronic use.",
    cautions: "Contraindicated when significant blood pressure elevation would be hazardous (uncontrolled hypertension, acute coronary syndrome, aortic dissection). Relative contraindications also include severe hepatic dysfunction, active psychosis, pregnancy, elevated intracranial/intraocular pressure. Benzodiazepines may be used to reduce emergence reactions.",
    pearl: "Ketamine is the only induction agent that increases blood pressure and heart rate through indirect sympathomimetic activity. However, ketamine is actually a direct myocardial depressant—the sympathetic stimulation masks this effect. In catecholamine-depleted states (severe sepsis, chronic heart failure, prolonged critical illness), ketamine can cause cardiovascular collapse because the indirect sympathetic effects cannot compensate for direct myocardial depression (NEJM, Casey et al, 2025).",
  },
  midazolam: {
    id: "midazolam",
    name: "Midazolam",
    class: "Benzodiazepine (water-soluble, short-acting)",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "Positive allosteric modulator of GABA-A receptors, enhancing inhibitory neurotransmission.",
    commonUse: "Preoperative sedation/anxiolysis/amnesia, procedural sedation, induction of general anesthesia, ICU sedation.",
    dose: "Preop sedation: 1-2.5 mg IV titrated slowly (≤5 mg total); 0.07-0.08 mg/kg IM.",
    onset: "IV: 3-5 minutes (induction: 1.5-2.5 min); IM: 15 minutes (peak 30-60 min).",
    duration: "15-80 minutes depending on dose (shorter than other benzodiazepines).",
    sideEffects: "Respiratory depression (23% IV), apnea (15% IV), hypotension, paradoxical agitation/combativeness, hiccoughs, nausea/vomiting, injection site pain.",
    cautions: "Profound respiratory depression with opioids—reduce midazolam dose by 30-50% when co-administered. Avoid rapid IV push. Patients with COPD are unusually sensitive to respiratory effects. Does NOT blunt the hemodynamic response to intubation. Have flumazenil (benzodiazepine antagonist) available.",
    pearl: "Midazolam is the only water-soluble benzodiazepine, which is why it doesn't burn on injection like diazepam. Also, midazolam provides excellent amnesia but minimal analgesia: 71-82% of patients have no recall of endoscopy procedures, yet they still require adequate analgesia for painful stimuli. Furthermore, pediatric patients paradoxically require higher doses than adults for sedation/anesthesia.",
  },
  // ── Paralytics ────────────────────────────────────────────────────────────
  rocuronium: {
    id: "rocuronium",
    name: "Rocuronium",
    class: "Non-depolarizing neuromuscular blocking agent (aminosteroid)",
    mechanism: "Competitive antagonist at nicotinic acetylcholine receptors at the motor end-plate; antagonized by acetylcholinesterase inhibitors (neostigmine, edrophonium).",
    commonUse: "Rapid sequence and routine tracheal intubation; skeletal muscle relaxation during surgery or mechanical ventilation.",
    dose: "Intubating dose commonly ~0.6–1.2 mg/kg IV depending on timing.",
    onset: "60-90 seconds at 0.6 mg/kg; faster with higher doses (excellent intubating conditions in <2 min).",
    duration: "~30-40 minutes at 0.6 mg/kg (intermediate duration); dose-dependent.",
    sideEffects: "Tachycardia (vagolytic effect), transient hypertension/hypotension, increased pulmonary vascular resistance, injection site reactions; anaphylaxis rare but can be fatal.",
    cautions: "Rocuronium is the most common cause of perioperative anaphylaxis among neuromuscular blockers—cross-reactivity exists between all NMBAs. Always have sugammadex available for emergent reversal. Monitor with peripheral nerve stimulator. Residual paralysis is a major concern—extubate only after adequate recovery (Train of Four Ratio > 0.9).",
    pearl: "Rocuronium has replaced succinylcholine as the preferred RSI paralytic in many institutions because of sugammadex availability. Sugammadex 16 mg/kg can fully reverse even profound rocuronium-induced block within 3 minutes, eliminating the historical advantage of succinylcholine's short duration. Also note: dose rocuronium based on ideal body weight in obese patients to avoid prolonged paralysis, unlike induction agents dosed on total body weight.",
  },
  succinylcholine: {
    id: "succinylcholine",
    name: "Succinylcholine",
    class: "Depolarizing neuromuscular blocking agent",
    mechanism: "Binds nicotinic acetylcholine receptors at the motor end-plate, causing sustained depolarization (observed as fasciculations) followed by neuromuscular blockade; metabolized by plasma cholinesterase.",
    commonUse: "Rapid sequence intubation (RSI), short procedures requiring muscle relaxation, electroconvulsive therapy.",
    dose: "Commonly ~1–1.5 mg/kg IV for RSI. Is also the only paralytic that can be given IM.",
    onset: "<1 minute IV",
    duration: "4-6 minutes (single dose).",
    sideEffects: "Fasciculations, bradycardia (especially with repeat dosing), hyperkalemia, increased intragastric/intraocular pressure, postoperative myalgias, masseter muscle rigidity, malignant hyperthermia, prolonged paralysis (pseudocholinesterase deficiency).",
    cautions: "Contraindicated in burns, crush injuries, denervation injuries, upper motor neuron lesions (after acute phase ~48-72 hours), and skeletal muscle myopathies due to risk of fatal hyperkalemia. Contraindicated in personal/family history of malignant hyperthermia or RYR1/CACNA1S variants. Pretreat with atropine to prevent bradycardia, especially with repeat doses.",
    pearl: "The earliest sign of malignant hyperthermia (often triggered by inhaled anesthetics + succinylcholine) is rising ETCO₂, not fever. Temperature elevation is often a late finding, and if you are waiting for it, you're behind (JAMA, Litman et al, 2005). The classic triad is unexplained hypercapnia + tachycardia + muscle rigidity, especially masseter spasm after succinylcholine.",
  },
  vecuronium: {
    id: "vecuronium",
    name: "Vecuronium",
    class: "Aminosteroid nondepolarizing neuromuscular blocking agent (intermediate-acting)",
    mechanism: "Competitive antagonist at nicotinic acetylcholine receptors at the motor end-plate → prevents acetylcholine binding → skeletal muscle paralysis. Reversed by acetylcholinesterase inhibitors (neostigmine, edrophonium, pyridostigmine).",
    commonUse: "Endotracheal intubation, surgical relaxation, mechanical ventilation.",
    dose: "Intubation: 0.08-0.1 mg/kg IV (intubating conditions in 2.5-3 min)",
    onset: "2.5-3 minutes (good intubating conditions); first twitch depression ~1 min",
    duration: "25-40 minutes (clinical duration to 25% recovery); 95% recovery ~45-65 min.",
    sideEffects: "Prolonged paralysis (most common adverse effect), rare anaphylaxis/hypersensitivity (bronchospasm, hypotension, urticaria), ICU-acquired weakness with prolonged use.",
    cautions: "Hepatic impairment prolongs recovery (hepatic metabolism/excretion). Renal failure generally well-tolerated if dialyzed; reduce dose in emergency anephric patients. Volatile anesthetics enhance blockade. No histamine release (hemodynamically stable). Cross-reactivity possible with other NMBAs. Always use nerve stimulator monitoring.",
    pearl: "The key advantage of vecuronium over rocuronium: no histamine release and excellent cardiovascular stability—it's essentially 'hemodynamically silent.' However, rocuronium has largely replaced vecuronium in most ORs because of faster onset (60-90 sec vs 2.5-3 min) and sugammadex reversibility. The main scenario where vecuronium still shines: patients where you want intermediate duration without cardiovascular effects and don't need rapid-sequence conditions.",
  },
  cisatracurium: {
    id: "cisatracurium",
    name: "Cisatracurium",
    class: "Benzylisoquinolinium nondepolarizing neuromuscular blocking agent (intermediate-acting)",
    mechanism: "Competitive antagonist at nicotinic acetylcholine receptors at the motor end-plate → prevents acetylcholine binding → skeletal muscle paralysis. Cisatracurium is the 1R-cis, 1'R-cis isomer of atracurium (~15% of atracurium mixture) and is ~3x more potent.",
    commonUse: "Endotracheal intubation, surgical relaxation, ICU paralysis for mechanical ventilation.",
    dose: "Intubation: 0.15-0.2 mg/kg IV (intubating conditions in ~2-3 min)",
    onset: "2-3 minutes (maximum block); good intubating conditions ~2.8 min at 0.1 mg/kg",
    duration: "28-36 minutes (clinical duration to 25% recovery); recovery rate independent of dose.",
    sideEffects: "Bradycardia (0.4%), hypotension (0.2%), flushing (0.2%), bronchospasm (0.2%), rash (0.1%). No clinically significant histamine release at recommended doses.",
    cautions: "Laudanosine metabolite can accumulate in renal/hepatic impairment with prolonged use (theoretical seizure risk in animals). Hypersensitivity/anaphylaxis possible, and cross-reactivity with other NMBAs. Neuromuscular diseases (myasthenia gravis) increase sensitivity. Multi-dose vials contain benzyl alcohol (avoid in neonates). Always use nerve stimulator monitoring.",
    pearl: "The defining feature of cisatracurium: organ-independent Hofmann elimination—it degrades spontaneously via pH- and temperature-dependent chemical degradation, independent of hepatic or renal function. This makes it the ideal NMBA for ICU patients with multiorgan failure. In a head-to-head ICU study, cisatracurium had only 2 cases of prolonged recovery (167-270 min) vs 13 cases with vecuronium (up to 33 hours). Also, hypothermia slows Hofmann degradation: reduce infusion rate by 50% during CABG with induced hypothermia.",
  },
  // ── Pressors and Hemodynamic Control ─────────────────────────────────────────────────────────────
  phenylephrine: {
    id: "phenylephrine",
    name: "Phenylephrine",
    class: "Sympathomimetic vasopressor - alpha-1 agonist",
    mechanism: "Selective alpha-1 adrenergic receptor agonist. It causes direct vascular smooth muscle vasoconstriction. No beta activity. Increases SVR, systolic/diastolic BP, and MAP. Reflex bradycardia occurs via vagal activation as BP rises.",
    commonUse: "Intraoperative hypotension from vasodilation (neuraxial or general anesthesia). Phenyleprhine is now preferred over ephedrine for spinal hypotension during cesareans because it causes less fetal acidosis.",
    dose: "Typical OR syringe: 100 mcg/mL (ready-to-use). Infusion: 0.5-1.4 mcg/kg/min (perioperative); up to 6 mcg/kg/min (septic shock)",
    onset: "Rapid (within minutes).",
    duration: "Effect persists up to 20 minutes; effective half-life ~5 minutes.",
    sideEffects: "Reflex bradycardia can significantly decrease cardiac output—use cautiously in patients dependent on heart rate for CO. Avoid in severe coronary artery disease (can precipitate angina), decompensated heart failure, and pulmonary hypertension.",
    cautions: "Severe uncontrolled hypertension, some tachyarrhythmia contexts.",
    pearl: "Phenylephrine is ideal for hypotension from pure vasodilation with preserved cardiac function—classic scenario is spinal anesthesia for cesarean section in a healthy patient. However, in patients who are bradycardic, have fixed stroke volume (aortic stenosis), or are dependent on HR for CO, ephedrine (which has beta activity and increases HR/contractility) or norepinephrine (alpha + some beta) may be better choices.",
  },
  ephedrine: {
    id: "ephedrine",
    name: "Ephedrine",
    class: "Sympathomimetic vasopressor - indirect alpha/beta agonist activity",
    mechanism: "Dual mechanism: (1) direct alpha-1, beta-1, and beta-2 agonist, and (2) indirect release of endogenous norepinephrine from sympathetic nerve terminals. Increases BP via vasoconstriction (alpha-1), increased HR and contractility (beta-1), and augmented cardiac output.",
    commonUse: "Intraoperative hypotension (especially with bradycardia), spinal anesthesia hypotension",
    dose: "5-10 mg IV bolus, repeat PRN. Max total dose can reach 50 mg, but tachyphylaxis limits effectiveness beyond this dose.",
    onset: "1-2 minutes IV.",
    duration: "Longer than phenylephrine bolus; tachyphylaxis with repeated dosing.",
    sideEffects: "Tachycardia, palpitations, hypertension, nausea/vomiting, ventricular ectopy, restlessness.",
    cautions: "Tachyphylaxis occurs with repeated dosing (depletes endogenous norepinephrine stores)—switch to direct-acting agent (phenylephrine, norepinephrine) if unresponsive. This consideration is especially relevant in elderly. Furthermore, be careful of potentiation effects by MAOIs or oxytocin, or arrhythmic effects in combination with halothane or digitalis.",
    pearl: "Ephedrine is your go-to when hypotension comes with bradycardia. Unlike phenylephrine (pure alpha), ephedrine's beta-1 activity increases heart rate and contractility while raising SVR, making it ideal for the bradycardic, hypotensive patient.",
  },
  norepinephrine: {
    id: "norepinephrine",
    name: "Norepinephrine",
    class: "Catecholamine vasopressor (alpha-1 predominant + beta-1 agonist)",
    mechanism: "Potent alpha-1 agonist (vasoconstriction) with modest beta-1 activity (maintains cardiac output). Increases SVR and MAP with minimal change in heart rate. Reflex bradycardia may occur as BP rises. Coronary blood flow increases secondary to alpha stimulation.",
    commonUse: "First-line vasopressor for septic shock, distributive shock, severe intraoperative hypotension refractory to bolus vasopressors.",
    dose: "Initial: 8-12 mcg/min IV infusion. Maintenance: 2-4 mcg/min (typical). Requires central line for prolonged infusions, but short-term infusions in PIV is okay in emergency.",
    onset: "Rapid; steady state in 5 minutes.",
    duration: "Pressor effect stops 1-2 minutes after discontinuation; half-life ~2.4 min.",
    sideEffects: "Reflex bradycardia, hypertension, arrhythmias (especially with hypoxia/hypercarbia), tissue ischemia, anxiety, headache, extravasation necrosis. Especially watch for excessive vasoconstriction at injection/IV sites.",
    cautions: "Correct hypovolemia first. Norepinephrine in hypovolemic patients causes severe vasoconstriction with decreased renal perfusion, lactic acidosis, and tissue hypoxia despite 'normal' BP. Extravasation causes tissue necrosis: infuse into a large vein, treat with phentolamine 5-10 mg if extravasation occurs.",
    pearl: "Norepinephrine is the ideal vasopressor when you need to raise BP without sacrificing cardiac output. Unlike phenylephrine (pure alpha), norepinephrine's modest beta-1 activity maintains CO while increasing SVR. This is why the Surviving Sepsis Campaign recommends it as first-line for septic shock over dopamine (which causes more arrhythmias) or phenylephrine (which can drop CO) (Critical Care Medicine, Evans et al, 2021 + NEJM, Vincent et al, 2013).",
  },
  vasopressin: {
    id: "vasopressin",
    name: "Vasopressin",
    class: "Non-catecholamine vasopressor (V1 receptor agonist / antidiuretic hormone analog)",
    mechanism: "Binds V1 receptors on vascular smooth muscle → vasoconstriction via intracellular calcium release. Also stimulates V2 receptors (antidiuresis). Increases SVR and MAP without relying on adrenergic receptors, which works even when catecholamines fail (acidosis impairs alpha-receptors but not V1 receptors).",
    commonUse: "Vasodilatory shock refractory to catecholamines (septic shock, post-cardiotomy vasoplegia), adjunct to norepinephrine.",
    dose: "Septic shock: 0.03 units/min.",
    onset: "Peak effect within 15 minutes.",
    duration: "Pressor effect fades within 20 minutes after stopping; no tachyphylaxis.",
    sideEffects: "Decreased cardiac output, bradycardia, arrhythmias (atrial fibrillation), hyponatremia, mesenteric ischemia, digital/skin ischemia, coronary ischemia.",
    cautions: "Decreases cardiac index—use cautiously in patients with poor cardiac function. Higher doses (>0.04 units/min) increase risk of splanchnic, digital, and cardiac ischemia. Reversible diabetes insipidus can occur after discontinuation (polyuria, hypernatremia).",
    pearl: "The Surviving Sepsis Campaign recommends adding vasopressin (typically 0.03 units/min) when norepinephrine reaches 0.25-0.5 mcg/kg/min to achieve a 'catecholamine-sparing' effect and potentially reduce arrhythmias.",
  },
  epinephrine:{
    id: "epinephrine",
    name: "Epinephrine",
    class: "Shock rescue / resuscitation agent with vasoconstrictor and inotropic effects through adrenergic receptors (alpha-1 predominant + beta-1)",
    mechanism: " Potent β₁, moderate β₂, and α₁-adrenergic agonist. α₁ → vasoconstriction, ↑SVR, ↑coronary/cerebral perfusion. β₁ → ↑ inotropy, ↑ chronotropy. β₂ → bronchodilation, vasodilation (skeletal muscle). At low doses: ↑ CO, ↓ SVR. At high doses: ↑ inotropy + vasoconstriction.",
    commonUse: "Cardiac arrest, anaphylaxis, severe hypotension/shock, bronchospasm, local anesthetic adjunct.",
    dose: "Cardiac arrest: 1 mg IV q3-5 min (standard ACLS); Anaphylaxis (IV bolus): 0.05-0.1 mg (50-100 mcg) slow push (1:10,000); Push-dose pressor: 10-20 mcg IV bolus; Infusion: 1-10 mcg/min (titrate to effect)",
    onset: "Immediate IV effect, 5-10 minutes for IM.",
    duration: "5-10 minutes (short half-life ~2 min).",
    sideEffects: "Tachycardia, arrhythmias (including VF), hypertension, anxiety, tremor, palpitations, headache, nausea, pallor, lactic acidosis (high doses), stress cardiomyopathy (rare).",
    cautions: "Use with caution in cardiac disease, arrhythmias, hypertension, hyperthyroidism, elderly. Halogenated anesthetics sensitize myocardium to arrhythmias, so use cautiously with halothane/sevoflurane. β-blockers antagonize cardiac effects. MAOIs/TCAs potentiate effects. Digital ischemia with accidental injection into digits. Despite cautions, no absolute contraindication in life-threatening anaphylaxis.",
    pearl: "The mnemonic: '1:10,000 for codes (cardiac arrest), 1:100,000 for loads (anaphylactic shock/hypotension). Remember that epinephrine increases ROSC in cardiac arrest but may not improve neurological outcomes—timing matters, with earlier administration associated with better survival. (Panchal et al, Circulation, 2020).'",
  },
  metoprolol: {
    id: "metoprolol",
    name: "Metoprolol",
    class: "β₁-selective (cardioselective) adrenergic receptor blocker: class II antiarrhythmic",
    mechanism: "Competitive antagonist at β₁-adrenergic receptors → ↓heart rate, ↓AV nodal conduction, ↓myocardial contractility, ↓myocardial oxygen demand. Cardioselective at lower doses; at higher concentrations also blocks β₂-receptors (bronchial/vascular).",
    commonUse: "Intraoperative tachycardia/hypertension, rate control (SVT, atrial fibrillation), perioperative cardiac protection in high-risk patients, hypertension, angina.",
    dose: "IV bolus: 2.5-5 mg IV over 2 min; may repeat q5 min (max 15 mg total).",
    onset: "1-2 minutes (IV).",
    duration: "5-8 hours (single IV dose). Metoprolol tartarate acts fast and wears off fast; succinate is an extended-release formulation that acts throughout the day.",
    sideEffects: "Bradycardia (6.6%), hypotension (15%), fatigue, dizziness, cold extremities, bronchospasm, nausea, nightmares, depression, sexual dysfunction.",
    cautions: "Sinus bradycardia, heart block (>1st degree), cardiogenic shock, decompensated HF. Avoid in bronchospasm diseases. Do not initiate high-dose metoprolol on day of surgery. Never abruptly discontinue in chronic users (risk of rebound angina/MI). Masks hypoglycemia symptoms in diabetics. May blunt response to epinephrine in anaphylaxis. Pheochromocytoma requires alpha-blockade first.",
    pearl: "The POISE trial is a landmark study that showed that high-dose metoprolol (100 mg) started on the day of surgery reduced perioperative MI but increased stroke (2x risk) and all-cause mortality (Smilowitz et al, JAMA, 2020): the mechanism appears to be perioperative hypotension. Continue β-blockers in patients already on them (abrupt withdrawal is dangerous), but do not start high-dose β-blockers on the day of surgery. If initiating perioperatively, start ≥1 week before surgery at low doses and titrate to heart rate.",
  },
  nicardipine: {
    id: "nicardipine",
    name: "Nicardipine",
    class: "Dihydropyridine calcium channel blocker (L-type)",
    mechanism: "Inhibits transmembrane influx of calcium ions into vascular smooth muscle and cardiac muscle via voltage-dependent L-type calcium channels. Predominantly acts on vascular smooth muscle → peripheral arterial vasodilation → ↓ SVR → ↓ BP. Minimal effect on cardiac conduction or contractility at therapeutic doses (unlike non-dihydropyridines).",
    commonUse: "Perioperative/postoperative hypertension, hypertensive emergencies, acute BP control when oral therapy not feasible.",
    dose: "IV infusion: Start 5 mg/hr; titrate by 2.5 mg/hr every 15 min (gradual) or every 5 min (rapid) to max 15 mg/hr.",
    onset: "Minutes; BP begins falling within minutes of starting infusion; reaches ~50% of ultimate effect in ~45 min.",
    duration: "30 min (50% offset after stopping); gradual antihypertensive effects persist for hours.",
    sideEffects: "Headache (13%), hypotension (5%), tachycardia (4%), nausea/vomiting (4%), peripheral edema, infusion site thrombophlebitis.",
    cautions: "Avoid in advanced aortic stenosis. Use caution in CHF (potential negative inotropy, especially with β-blockers), hepatic impairment (↑ levels 4x), renal impairment (↑ levels 2x). Avoid small veins (dorsum of hand/wrist, can cause phlebitis. Change peripheral IV site every 12 hours. Does not protect against β-blocker withdrawal, must taper β-blockers separately.",
    pearl: "Nicardipine is the workhorse IV antihypertensive in the OR and neuro-ICU. For postoperative hypertension, mean time to therapeutic response is only 12 minutes with an average maintenance dose of just 3 mg/hr, much lower than severe HTN (8 mg/hr). Always change peripheral IV sites every 12 hours to prevent thrombophlebitis, or use a central line.",
  },
  esmolol: {
    id: "esmolol",
    name: "Esmolol",
    class: "β₁-selective (cardioselective) adrenergic receptor blocker: class II antiarrhythmic",
    mechanism: "Competitive antagonist at β₁-adrenergic receptors → ↓heart rate, ↓AV conduction, ↓contractility. Cardioselective at therapeutic doses; at higher doses also inhibits β₂-receptors. No intrinsic sympathomimetic or membrane-stabilizing activity.",
    commonUse: "Perioperative tachycardia/hypertension (intubation, extubation), SVT rate control, atrial fibrillation/flutter, noncompensatory sinus tachycardia, electroconvulsive therapy.",
    dose: "Supraventricular Tachycardia: Step-wise dosing with optional loading dose (500 mcg/kg over 1 minute), then 50 mcg/kg/min for 4 min, increasing by 50 mcg/kg/min at each step; Intraoperative and Postoperative Tachycardia and Hypertension: 1 mg/kg as a bolus dose over 30 seconds followed by an infusion of 150 mcg/kg/min if necessary, titrate to effect.",
    onset: "Ultra-fast-acting, 1-2 minutes.",
    duration: "10-20 minutes after stopping infusion (t½ ~9 min)",
    sideEffects: "Hypotension (25% asymptomatic, 12% symptomatic), infusion site reactions (8%), nausea (7%), dizziness, somnolence, bradycardia.",
    cautions: "Hypotension is dose-related: reduce/stop if BP drops. Avoid in decompensated HF, cardiogenic shock, severe bradycardia. Use cautiously in reactive airway disease (though safer than non-selective β-blockers). Masks hypoglycemia. Pheochromocytoma requires an alpha blockade first. Avoid abrupt discontinuation in CAD patients.",
    pearl: "The key advantage of esmolol is its metabolism by RBC esterases, not plasma cholinesterases or hepatic enzymes, giving it organ-independent clearance unaffected by liver/kidney dysfunction. It is ideal for a tight control with a quick off-switch. Furthermore, a 2025 meta-analysis showed esmolol infusion reduces intraoperative opioid consumption by 32% and postoperative opioid use by 39%, with lower pain scores, making it a legitimate opioid-sparing adjunct in multimodal anesthesia (Neto et al, Anesthesia and Analgesia, 2025).",
  },
  hydralazine: {
    id: "hydralazine",
    name: "Hydralazine",
    class: "Direct-acting arterial vasodilator",
    mechanism: "Relaxes vascular smooth muscle by altering cellular calcium metabolism, interfering with calcium movements responsible for the contractile state. Preferentially dilates arterioles (not veins) → ↓ SVR → ↓ BP (diastolic > systolic). Triggers reflex sympathetic activation → ↑ HR, ↑ stroke volume, ↑ cardiac output. Also activates RAAS (↑ renin, ↑ aldosterone).",
    commonUse: "Severe hypertension when oral therapy not feasible, hypertensive emergencies (especially pregnancy/preeclampsia), HFrEF (combined with the fantastic four GDMT as adjunct, along with nitrates)",
    dose: "IV/IM: 10-20 mg initial dose; repeat every 4-6 h as needed.",
    onset: "10-20 minutes (IV); maximal effect 10-80 min.",
    duration: "2-4 hours",
    sideEffects: "Headache, tachycardia, palpitations, flushing, nausea/vomiting, hypotension, angina, peripheral edema. Drug-induced lupus (chronic use). Peripheral neuritis (treat with pyridoxine).",
    cautions: "Use cautiously in CAD (reflex tachycardia → myocardial ischemia/MI). Avoid in mitral valve disease (↑pulmonary artery pressure), aortic dissection. Caution in cerebrovascular disease (rapid BP drop → ischemia). Monitor ANA titers with chronic use (drug-induced lupus and ANCA-associated vasculitis (Fremont et al, JAMA, 2026), remember the mnemonic HEAPS PIMP).",
    pearl: "The 2025 ACC/AHA guidelines explicitly state that hydralazine is an 'undesirable first-line agent' for acute hypertension due to unpredictable response and prolonged duration of action. The problem: you give 10-20 mg IV, wait 10-80 minutes for peak effect, and if BP drops too much, you're stuck for 2-4 hours with no off-switch. For perioperative BP control, titratable agents (nicardipine, clevidipine, esmolol) are far superior. The one exception: pregnancy-related hypertension, where hydralazine remains a first-line option alongside labetalol, nifedipine, and methyldopa (remember the mnemonic 'He Likes My Neonate').",
  },
  // ── Reversal / rescue ─────────────────────────────────────────────────────
  sugammadex: {
    id: "sugammadex",
    name: "Sugammadex",
    class: "Selective relaxant binding agent (modified gamma-cyclodextrin)",
    mechanism: "Encapsulates aminosteroid NMBAs (rocuronium > vecuronium >> pancuronium) in a 1:1 ratio within its ring-like structure. Creates a plasma concentration gradient that pulls rocuronium/vecuronium away from the neuromuscular junction back into plasma, where it's trapped and renally excreted.",
    commonUse: "Rapid reversal of rocuronium/vecuronium-induced block.",
    dose: "Block depth dependent. Moderate blocks (T2 reappears): 2 mg/kg IV. Deep blocks (1-2 Post Tetanic Counts on no Train of Four responses): 4 mg/kg IV. Immediate reversals (3 min after rocuronium 1.2 mg/kg): 16 mg/kg IV. Make sure to use actual body weight, including in obese patients.",
    onset: "Recovery to TOF ≥0.9 in ~2-3 minutes (vs. 10-15+ min with neostigmine).",
    duration: "Reversal effect: rocuronium remains encapsulated and excreted renally.",
    sideEffects: "Hypersensitivity/anaphylaxis (~0.3% in studies), bradycardia, bronchospasm, nausea/vomiting, dysgeusia.",
    cautions: "Anaphylaxis can occur even on first exposure. It is more common in women, with reports indicating a ratio of approximately 3:1. Some theories suggest it is because women are exposed to various cosmetics or soaps/household cleaners that contain a similar quatenary ammonium structure. Also binds steroidal hormones, including hormonal contraceptives - equivalent to missing one pill, so advise patients to use backup contraceptives for 7 days.",
    pearl: "Always use quantitative neuromuscular monitoring (TOF ratio ≥0.9) before extubation. Even with sugammadex, rare cases of delayed or incomplete reversal occur, and clinical assessment alone misses residual paralysis (Anesthesiology, Thilen et al, 2023).",
  },
  neostigmine: {
    id: "neostigmine",
    name: "Neostigmine",
    class: "Acetylcholinesterase inhibitor",
    mechanism: " Competitively inhibits acetylcholinesterase → increases acetylcholine at the neuromuscular junction → acetylcholine outcompetes nondepolarizing NMBAs for receptor binding → reverses blockade.",
    commonUse: "Reversal of nondepolarizing neuromuscular blockade (rocuronium, vecuronium, cisatracurium, atracurium). Only option for benzylisoquinoliniums (cisatracurium/atracurium, because sugammadex doesn't work on these.",
    dose: "Block depth dependent. Minimal blocks (Train of Four ratio >0.4): 0.03 mg/kg. Moderate blocks (T1 > 10% at baseline: 0.03-0.07 mg/kg. Maximal blocks: 0.07 mg/kg or 5 mg total, whichever is less. Always co-administer an anticholinergic like glycopyrrolate ~10 mcg/kg or atropine ~15 mcg/kg. (Anesthesiology, Thilen et al, 2023)",
    onset: "Peak effect in ~10 minutes.",
    duration: "Elimination half-life 24-113 minutes; effect duration depends on NMBA clearance.",
    sideEffects: "Must give anticholinergic (glycopyrrolate or atropine) to prevent bradycardia and muscarinic effects. Unlike sugammadex, cannot reliably reverse deep block, often requiring TOF count ≥1 (ideally TOF ratio ≥0.4) for reliable reversal. Also has a ceiling effect - doses above 50 mcg/kg are often not effective.",
    cautions: "Avoid reversing deep block; airway complications if rushed.",
    pearl: "The ASA guidelines emphasize that neostigmine should ideally be given at TOF ratio ≥0.4 ('minimal block') for reliable reversal within 10 minutes. If you give neostigmine at TOF count of 2, you may be waiting 20-30+ minutes for adequate recovery. Neostigmine peaks at 10 minutes, so that extra time is just waiting for spontaneous recovery, not neostigmine working harder (Anesthesiology, Thilen et al, 2023).",
  },
  glycopyrrolate: {
    id: "glycopyrrolate",
    name: "Glycopyrrolate",
    class: "Anticholinergic / antimuscarinic (quaternary ammonium compound)",
    mechanism: "Blocks muscarinic receptors → prevents acetylcholine effects at postganglionic cholinergic nerve endings. Reduces secretions (salivary, tracheobronchial, pharyngeal, gastric), blocks vagal cardiac reflexes (prevents bradycardia), and antagonizes muscarinic side effects of anticholinesterases. The quaternary ammonium structure does not cross the blood-brain barrier. Unlike atropine, glycopyrrolate causes minimal CNS effects.",
    commonUse: "Paired with neostigmine for NMB reversal (prevents bradycardia/secretions), preanesthetic antisialagogue, intraoperative treatment of vagal-induced bradycardia.",
    dose: "Reversal of NMB: 0.2 mg per 1 mg neostigmine. Intraoperative bradycardia: 0.1 mg IV, repeat q2-3 min PRN.",
    onset: "IV onset within 1 minute.",
    duration: "Vagal blocking effects 2-3 hours; antisialagogue effects up to 7 hours (longer than atropine).",
    sideEffects: "Tachycardia, dry mouth (xerostomia), urinary retention, blurred vision/mydriasis, decreased sweating, constipation, drowsiness, arrhythmias (including bradycardia, heart block, QTc prolongation when combined with anticholinesterases)",
    cautions: "Contraindicated in myasthenia gravis, mechanical GI obstruction, paralytic ileus, and narrow-angle glaucoma. Use with caution in CAD, CHF, arrhythmias, HTN, hyperthyroidism, and renal impairment (renally excreted).",
    pearl: "As a quaternary ammonium compound, glycopyrrolate cannot cross the blood-brain barrier, so you avoid the confusion, sedation, and delirium that atropine (a tertiary amine) can cause: especially important in elderly patients.",
  },
  naloxone: {
    id: "naloxone",
    name: "Naloxone",
    class: "Opioid antagonist",
    mechanism: "Competitively displaces opioids from receptors → reverses respiratory depression, sedation, and hypotension. Unlike mixed agonist-antagonists, naloxone has no intrinsic opioid activity.",
    commonUse: "Opioid-induced respiratory depression or overdose.",
    dose: "40 - 200 mcg IV and repeat q2-3 min PRN. Max total dose 10 mg.",
    onset: "Rapid IV within 2 minutes.",
    duration: "May be shorter than long-acting opioids (30-90 minutes) — re-sedation possible.",
    sideEffects: "Nausea, vomiting, sweating, tachycardia, hypertension, tremulousness, agitation, seizures, ventricular tachycardia/fibrillation, pulmonary edema, cardiac arrest.",
    cautions: "Renarcotization: naloxone's duration is shorter than most opioids, so respiratory depression may recur; continued surveillance and repeat dosing required. Furthermore, precipitates acute withdrawal within minutes (lasts ~2 hours).",
    pearl: "Titrate, don't slam. In the postoperative setting, the goal is to reverse respiratory depression while preserving analgesia—this requires small incremental doses (0.04–0.1 mg IV, even smaller than the label's 0.1–0.2 mg) titrated every 2-3 minutes.",
  },
  flumazenil: {
    id: "flumazenil",
    name: "Flumazenil",
    class: "Benzodiazepine antagonist",
    mechanism: "Competitively inhibits benzodiazepines at the GABA-A receptor binding site → reverses sedation, amnesia, psychomotor impairment, and respiratory depression.",
    commonUse: "Reversal of benzodiazepine-induced sedation (procedural sedation, general anesthesia), management of benzodiazepine overdose.",
    dose: "Procedural sedation reversal: 0.2 mg IV over 15 sec, repeat q1 min PRN (max 1 mg total). Overdose: 0.2 mg IV over 30 sec, then 0.3 mg, then 0.5 mg increments q30 sec (max 3 mg total).",
    onset: "Rapid 1-2 minutes.",
    duration: "40-80 minutes (terminal half-life); resedation risk with long-acting benzodiazepines.",
    sideEffects: "Seizure risk in chronic benzodiazepine dependence or mixed overdoses. Also may cause nausea, vomiting, dizziness, agitation, dysrhythmias like SVT, ventricular, asystole, and withdrawal symptoms.",
    cautions: "Seizure risk is the major concern: avoid in patients on chronic benzos, epileptics on benzodiazepine therapy, and suspected TCA overdoses. Also use with caution in patients with head injury and hepatic impairment (prolonged half life in severe liver disease).",
    pearl: "Flumazenil is safe in controlled settings, dangerous in unknown overdoses. In procedural sedation where you gave the midazolam yourself, flumazenil is low-risk and effective. But in the ED with an unknown overdose, flumazenil can be deadly. It unmasks TCA cardiotoxicity (wide QRS, arrhythmias) and precipitates refractory seizures in benzodiazepine-dependent patients. AHA guidelines state that if you suspect any co-ingestion (opioids, TCAs, alcohol), it may be safer to give naloxone (Circulation, Lavonas et al, 2023).",
  },
  diphenhydramine: {
    id: "diphenhydramine",
    name: "Diphenhydramine",
    class: "First generation H1 antihistamine / anaphylaxis rescue",
    mechanism: "Competitive antagonist at H1 histamine receptors on effector cells → blocks histamine-mediated allergic responses. Also has significant anticholinergic (muscarinic) activity and CNS sedation via crossing the blood-brain barrier.",
    commonUse: "Allergic reactions (urticaria, angioedema), anaphylaxis adjunct (after epinephrine), transfusion reactions, drug-induced dystonia/EPS, sedation adjunct, pruritus.",
    dose: "Adult: 25-50 mg IV (max 400 mg/day), administer at rate ≤25 mg/min; Pediatrics: 5 mg/kg/24 hr or 150 mg/m²/24 hr (max 300 mg/day); Anaphylaxis adjunct: 25-50 mg IV (after epinephrine)",
    onset: "Rapid (minutes IV); peak effect ~1 hour",
    duration: "4-6 hours",
    sideEffects: "Sedation/drowsiness (most common), dry mouth, blurred vision, urinary retention, tachycardia, hypotension, dizziness, confusion, paradoxical excitation (pediatrics)",
    cautions: "Narrow-angle glaucoma, BPH/urinary retention, stenosing peptic ulcer, pyloroduodenal obstruction. Contraindicated in neonates/premature infants. Elderly more susceptible to sedation/hypotension. Additive CNS depression with opioids/benzodiazepines. MAOIs intensify anticholinergic effects. Avoid subcutaneous/intradermal injection (causes local necrosis).",
    pearl: "Diphenhydramine as a sedation adjunct reduces opioid and benzodiazepine requirements. In a randomized trial of 270 colonoscopy patients, adding 50 mg diphenhydramine reduced meperidine requirements by ~10% and midazolam by ~15% with better sedation scores and no prolonged recovery. Diphenhydramine has a modest stimulatory effect on ventilation and may actually counteract opioid-induced hypoventilation. It can also be used for acute dystonic reactions. However, in elderly patients, diphenhydramine contributes to postoperative delirium risk.",
  },
  ketorolac: {
    id: "ketorolac",
    name: "Ketorolac",
    class: "Nonsteroidal anti-inflammatory drug (NSAID) / antiemetic",
    mechanism: "Inhibits prostaglandin synthetase (cyclooxygenase), blocking prostaglandin biosynthesis. The S-enantiomer is the active form. Possesses potent analgesic activity with no sedative or anxiolytic properties.",
    commonUse: "Short-term (≤5 days) management of moderately severe acute pain requiring opioid-level analgesia, usually postoperative. Part of multimodal analgesia to reduce opioid requirements.",
    dose: "Single-dose IV - <65 yo: 30 mg; ≥65 y/renal impairment/<50 kg: 15 mg.",
    onset: "~30 minutes; peak effect 1-2 hours",
    duration: "4-6 hours",
    sideEffects: "Nausea, dyspepsia, GI pain/bleeding, headache, dizziness, drowsiness, edema, injection site pain. Serious: GI ulceration/perforation, renal impairment, bleeding, CV thrombotic events.",
    cautions: "Contraindicated in: active/history of peptic ulcer or GI bleeding, CABG surgery, advanced renal impairment/volume depletion, cerebrovascular bleeding, hemorrhagic diathesis, labor/delivery, concurrent aspirin/NSAIDs, neuraxial administration (contains alcohol). Use caution in elderly, coagulation disorders, patients on anticoagulants, CHF, hepatic dysfunction, IBD.",
    pearl: "Ketorolac is for postoperative pain, NOT preoperative prophylaxis—it's explicitly contraindicated as prophylactic analgesic before major surgery due to bleeding risk. Also remember the 'rule of 15s and 30s': for elderly, renal impairment, or <50 kg patients, cut the dose in half (15 mg IV instead of 30 mg). Finally, the 5-day limit is absolute: exceeding it dramatically increases GI and renal adverse events.",
  },
  // ── Supportive ────────────────────────────────────────────────────────────
  lidocaine: {
    id: "lidocaine",
    name: "Lidocaine",
    class: "Amide local anesthetic / Class 1B antiarrhythmic",
    mechanism: "Weak sodium channel blockade. Prevents depolarization and nerve impulse conduction. As a local anesthetic, reversibly binds Na+ channels in peripheral nerves. As an antiarrhythmic, decreases automaticity in Purkinje fibers, shortens action potential duration, and raises ventricular fibrillation threshold with minimal hemodynamic effects. depolarization and nerve impulse conduction.",
    commonUse: "Local/regional anesthesia (infiltration, nerve blocks, epidural, spinal), IV regional anesthesia (Bier block), ventricular arrhythmias, IV adjunct for blunting laryngoscopy response.",
    dose: "Indication-specific, from local anesthesia, to IV regional (Bier Block), eto epidurals, to antiarrhythmics..",
    onset: "Infiltration <2 minutes; epidural 5-15 min; IV immediate.",
    duration: "30-60 minutes infiltration, 60-90 min with epidurals.",
    sideEffects: "CNS toxicity (perioral numbness, tinnitus, metallic taste, agitation, seizures), cardiovascular toxicity (bradycardia, hypotension, arrhythmias, cardiac arrest), methemoglobinemia (rare) (Circulation, Lavonas et al, 2023).",
    cautions: "LAST (local anesthetic systemic toxicity) is the major concern—CNS symptoms (perioral numbness, tinnitus, seizures) typically precede cardiovascular collapse.",
    pearl: "Know the max dose cold (4.5 mg/kg plain, 7 mg/kg with epi) and recognize early LAST signs. CNS toxicity (perioral numbness, tinnitus, metallic taste, agitation) occurs at lower plasma levels than cardiovascular toxicity. These are your warning signs before seizures and cardiac arrest.",
  },
  ondansetron: {
    id: "ondansetron",
    name: "Ondansetron",
    class: "5-HT3 receptor antagonist (antiemetic)",
    mechanism: "Selective 5-HT₃ receptor antagonist → blocks serotonin at vagal afferents (peripherally) and chemoreceptor trigger zone (centrally). Not a dopamine antagonist, so no extrapyramidal effects.",
    commonUse: "PONV prophylaxis/treatment, radiation-induced nausea (for rad onc procedures).",
    dose: "PONV prophylaxis: 4 mg IV over 30 sec–5 min at induction (or end of surgery).",
    onset: "30 minutes IV.",
    duration: "4-8 hours.",
    sideEffects: "Headache (most common), constipation, dizziness, QT prolongation (dose-dependent), rare serotonin syndrome with serotonergic drugs.",
    cautions: "Avoid in congenital long QT syndrome. QT prolongation is dose-dependent—use caution with electrolyte abnormalities (hypokalemia, hypomagnesemia), heart failure, bradyarrhythmias, or concurrent QT-prolonging drugs. Cases of Torsades de Pointes have been reported.",
    pearl: "The QT prolongation concern is real but often overstated at standard PONV doses. A 2026 systematic review of 170 RCTs (n=23,421) found no increased mortality or arrhythmias with ondansetron vs placebo: only 7 MACE events (all deaths, not arrhythmias) were reported (Clinical Pharmacology and Therapeutics, Garcia et al, 2026).",
  },
  dexamethasone: {
    id: "dexamethasone",
    name: "Dexamethasone",
    class: "Corticosteroid",
    mechanism: "Multiple antiemetic mechanisms → (1) anti-inflammatory effect reducing prostaglandins, (2) direct central action at solitary tract nucleus, (3) interaction with serotonin/NK1 receptors, (4) reducing opioid requirements (thus reducing opioid-induced nausea).",
    commonUse: "PONV prophylaxis, airway edema concerns, antiemetic adjunct.",
    dose: "PONV prophylaxis: 4-8 mg IV at induction (SAMBA recommends 4-5 mg; 8 mg commonly used).",
    onset: "1-2 hours (give at induction, not end of case).",
    duration: "24-72 hours.",
    sideEffects: "Transient hyperglycemia, mood effects, perineal itching/burning with rapid IV push, infection concern at higher/chronic exposure (Cochrane, Polderman et al, 2018).",
    cautions: "Use caution in diabetics (more pronounced glucose elevation).",
    pearl: "Concerns about infection risk and wound healing appear unfounded at single perioperative doses: meta-analyses show no increased surgical site infection (Peto OR 1.01) (Cochrane, Polderman et al, 2018 + Anesthesiology, Toner et al, 2017 + NEJM, Corcoran et al, 2021).",
  },
  atropine: {
    id: "atropine",
    name: "Atropine",
    class: "Anticholinergic / antimuscarinic (tertiary amine)",
    mechanism: "Competitively blocks muscarinic receptors → antagonizes acetylcholine at postganglionic cholinergic nerve endings (exocrine glands, smooth muscle, cardiac muscle). Unlike glycopyrrolate, atropine is a tertiary amine that crosses the blood-brain barrier → can cause CNS effects (stimulation at low doses, delirium at high doses).",
    commonUse: "Symptomatic bradycardia, antisialagogue (preanesthetic), paired with neostigmine for NMB reversal, organophosphate/carbamate poisoning antidote.",
    dose: "Symptomatic bradycardia: 0.5 mg IV q3-5 min (max 3 mg total).With neostigmine: ~15 mcg/kg (or ~1 mg per 2.5 mg neostigmine).",
    onset: "IV <1 minute; peak HR effect 2-4 minutes.",
    duration: "Vagolytic effect ~1 hour (shorter than glycopyrrolate's 2-3 hours).",
    sideEffects: "Tachycardia, dry mouth, blurred vision/mydriasis, photophobia, urinary retention, constipation, anhidrosis (heat intolerance), CNS effects (restlessness, confusion, delirium, hallucinations at high doses).",
    cautions: "Paradoxical bradycardia can occur with low doses (<0.5 mg in adults)—always give at least 0.5 mg. In ischemic heart disease, limit total dose to 2-3 mg (max 0.03-0.04 mg/kg) to avoid tachycardia-induced ischemia. Avoid in narrow-angle glaucoma, prostatic hypertrophy due to urinary retention risk, and pyloric stenosis. Does not work in transplanted hearts because of denervation - no vagal tones to block.",
    pearl: "Although glycopyrrolate is often preferred for NMB reversal due to atropine's shorter duration that may lead to late bradycardia, atropine has a faster onset that makes it better choice for acute intraoperative bradycardia. Also, remember that atropine does cross the BBB, meaning it can cause delirium in elderly patients.",
  },
  cefazolin: {
    id: "cefazolin",
    name: "Cefazolin",
    class: "First-generation cephalosporin (β-lactam antibiotic)",
    mechanism: "Bactericidal agent that inhibits bacterial cell wall synthesis. Active against gram-positive cocci (S. aureus, S. epidermidis, streptococci) and some gram-negatives (E. coli, P. mirabilis, Klebsiella - mnemonic is 'PEcK'). MRSA is uniformly resistant.",
    commonUse: "Perioperative surgical prophylaxis (most common anesthesia use), skin/soft tissue infections, respiratory infections, UTIs, endocarditis prophylaxis.",
    dose: "Weight below 120 kg: 2 g IV before incision; Above 120 kg: 3 g IV before incision; Redosing: 500 mg–1 g every 3-4 hours intraoperatively (for cases >2 hours); Postop: 500 mg–1 g q6-8h × 24 hours (up to 3-5 days for cardiac/prosthetic surgery).",
    onset: "Rapid, peak serum ~185 mcg/mL after 1 g IV.",
    duration: " t½ ~1.8 hours; redose q3-4h intraoperatively.",
    sideEffects: "Nausea/vomiting, diarrhea, rash, anaphylaxis, eosinophilia, transient ↑LFTs, phlebitis at injection site, C. diff colitis, seizures (high doses in renal impairment).",
    cautions: "Although cephalosporins traditionally have low cross-reactivity, it is still contraindicated in cephalosporin/penicillin anaphylaxis (cross-reactivity ~1-10%). Reduce dose in renal impairment (CrCl 55 mL/min). Monitor PT in patients on anticoagulants (↓prothrombin activity). Caution in GI disease history (colitis risk).",
    pearl: "Current evidence supports that cefazolin is safe in patients with non-anaphylactic penicillin allergies (e.g., rash, GI upset), and true cross-reactivity is ~1%, which is far lower than the historical 10% figure. However, avoid in patients with documented IgE-mediated penicillin anaphylaxis.",
  },
  // ── Controlled substances (in the locked grid) ───────────────────────────
  fentanyl: {
    id: "fentanyl",
    name: "Fentanyl",
    class: "Opioid — synthetic phenylpiperidine",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; highly lipophilic. 100 mcg fentanyl ≈ 10 mg morphine ≈ 75 mg meperidine.",
    commonUse: "Premedication, induction/maintenance of anesthesia, intraoperative analgesia, blunting hemodynamic response to laryngoscopy, postoperative pain control.",
    dose: "Dosing is dependent on clinical context and surgery, especially between cardiac surgeries (which predominantly uses opioid-based anesthesia) versus general surgical anesthesia.",
    onset: "IV almost immediately, IM 7-8 minutes.",
    duration: "30-60 minutes (single IV dose up to 100 mcg); IM: 1-2 hours.",
    sideEffects: "Respiratory depression, apnea, bradycardia, chest wall rigidity ('wooden chest'), hypotension, nausea/vomiting, laryngospasm, pruritus; secondary rebound respiratory depression postoperatively.",
    cautions: "Peak respiratory depression occurs 5-15 minutes after IV injection—outlasts analgesic effect. Reduce dose in elderly/debilitated patients. CYP3A4 inhibitors (azoles, macrolides, protease inhibitors) increase fentanyl levels. Avoid rapid high-dose boluses (causes chest wall rigidity). Have naloxone available.",
    pearl: "The dreaded 'wooden chest' syndrome (truncal rigidity) occurs with rapid, high-dose fentanyl boluses and can make bag-mask ventilation impossible—treat with neuromuscular blockade, not naloxone. Respiratory depression outlasts analgesia—altered CO₂ sensitivity persists up to 4 hours after a single 600 mcg dose, even when the patient appears comfortable.",
  },
  hydromorphone: {
    id: "hydromorphone",
    name: "Hydromorphone (Dilaudid)",
    class: "Opioid — semi-synthetic phenanthrene derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Full mu-opioid receptor agonist; approximately mu-opioid receptor agonist; approximately 5x more potent than morphine.",
    commonUse: "Moderate-to-severe postoperative pain, transition analgesia from remifentanil, PCA, neuraxial analgesia.",
    dose: "IV: 0.2-1 mg every 2-3 hours (start low: 0.2-0.4 mg). If hepatic and renal impairment, reduce dose by 50%.",
    onset: "IV: ~5 minutes; peak effect ~20 minutes.",
    duration: "2-3 hours (elimination half-life ~2.3 hours).",
    sideEffects: "Respiratory depression, hypotension, bradycardia, nausea/vomiting, pruritus, sedation, sphincter of Oddi spasm.",
    cautions: "Give IV doses slowly. Reduce doses in elderly/cachectic patients. Metabolized via glucuronidation (not CYP450), with fewer drug interactions than fentanyl, but metabolite (hydromorphone-3-glucuronide) accumulates in renal failure and may cause neuroexcitation.",
    pearl: "The key advantage of hydromorphone over morphine in the perioperative setting is its lack of active metabolites that accumulate in renal impairment. Morphine-6-glucuronide causes prolonged sedation/respiratory depression in renal failure, while hydromorphone-3-glucuronide is neuroexcitatory but less clinically problematic at typical doses.",
  },
  morphine: {
    id: "morphine",
    name: "Morphine",
    class: "Opioid — natural phenanthrene derived from opium poppy",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Full mu-opioid receptor agonist (relatively selective for mu, binds other receptors at higher doses). Metabolized via hepatic glucuronidation to morphine-3-glucuronide (M3G, inactive) and morphine-6-glucuronide (M6G, active analgesic).",
    commonUse: "Severe postoperative pain, neuraxial analgesia (intrathecal/epidural), PCA, transition analgesia.",
    dose: "IV bolus: 0.1-0.2 mg/kg every 4 hours (typically 2-4 mg increments). IV infusion: 0.02-0.1 mg/kg/hour (max 10 mg/hr opioid-naïve).",
    onset: "IV: 5-10 minutes; peak ~20 minutes.",
    duration: "3-4 hours (elimination half-life 1.5-2 hours).",
    sideEffects: "Respiratory depression, hypotension, nausea/vomiting, constipation, pruritus (especially neuraxial), sedation, urinary retention, histamine release.",
    cautions: "Avoid in renal failure due to M6G accumulation. Contraindicated with MAOIs (within 14 days) due to risk of serotonin syndrome. Histamine release could lead to hypotension, bronchospasm, pruritus (unlike fentanyl). Low oral bioavailability (~30%), thus unpredictable PO dosing.",
    pearl: "Morphine's active metabolite M6G accumulates in renal impairment, causing delayed respiratory depression hours after the last dose—this is why hydromorphone or fentanyl are preferred in patients with CKD.",
  },
  lorazepam: {
    id: "lorazepam",
    name: "Lorazepam (Ativan)",
    class: "Benzodiazepine",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "GABA-A receptor positive allosteric modulator. Enhances GABA affinity for its receptor, increasing chloride conductance and neuronal inhibition. Does not displace GABA.",
    commonUse: "Preoperative anxiolysis, amnesia for perioperative events, status epilepticus, ICU sedation or agitation.",
    dose: "IV (sedation/anxiolysis): 0.02-0.044 mg/kg (typically 2 mg, max 4 mg).",
    onset: " IV: 1-5 minutes (peak amnesia 15-20 min).",
    duration: "Clinical effects 6-8 hours; elimination half-life ~14 hours.",
    sideEffects: "xcessive sedation/drowsiness, respiratory depression, airway obstruction, hypotension, paradoxical agitation, confusion, hallucinations (~1%), nausea.",
    cautions: "Patients >50 years have significantly higher incidence of excessive sedation. IV formulation contains propylene glycol—risk of toxicity with prolonged high-dose infusions (metabolic acidosis, renal failure).",
    pearl: "Lorazepam infusions can predispose to propylene glycol toxicity and severe metabolic acidosis.",
  },
  meperidine: {
    id: "meperidine",
    name: "Meperidine (Demerol)",
    class: "Opioid — synthetic phenylpiperidine derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid agonist with actions qualitatively similar to morphine. Also has weak local anesthetic properties and anticholinergic effects. Metabolized by CYP3A4/CYP2B6 to normeperidine—a neuroexcitatory metabolite with half-life 3-6x longer than parent drug.",
    commonUse: "Preoperative medication, anesthesia support, obstetrical analgesia, post-anesthesia shivering (largely replaced by safer alternatives).",
    dose: "Shivering: 12.5-25 mg IV.Pain: 50-150 mg IM/SC q3-4h (25-50 mg IV for sedation).",
    onset: "IV: 1-5 minutes; IM: 10-15 minutes.",
    duration: "1-3 hours (shorter than morphine); half-life 2-5 hours (normeperidine: 15-30 hours).",
    sideEffects: "Respiratory depression, nausea, hypotension, tachycardia (vagolytic), seizures (normeperidine accumulation).",
    cautions: "Absolutely contraindicated with MAOIs: can cause fatal excitatory syndrome (agitation, rigidity, hyperthermia, seizures, death). Thus, also avoid in renal impairment due to normeperidine accumulation.",
    pearl: "Meperidine has no role in modern anesthesia practice except for one niche indication—post-anesthesia shivering (12.5-25 mg IV). Otherwise, it is strictly inferior opioid with a uniquely dangerous metabolite.",
  },
  remifentanil: {
    id: "remifentanil",
    name: "Remifentanil (Ultiva)",
    class: "Opioid — esterase-metabolized piperidine derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Mu-opioid receptor agonist; uniquely metabolized by nonspecific blood and tissue esterases (not plasma cholinesterase), patients with pseudocholinesterase deficiency have normal duration.",
    commonUse: "Analgesia during induction/maintenance of general anesthesia, monitored anesthesia care, immediate postoperative analgesia.",
    dose: "Induction bolus: 1 mcg/kg over 30-60 seconds. Maintenance: 0.05-2 mcg/kg/min (titrate to effect). Elderly must reduce starting dose by 50%.",
    onset: "Blood-brain equilibration half-time ~1 minute.",
    duration: "Context-sensitive half-time 3-6 minutes regardless of infusion duration with no accumulation even after 12-hour infusions.",
    sideEffects: "Hypotension (19%), muscle rigidity (11%), bradycardia (7%), respiratory depression, nausea/vomiting, opioid-induced hyperalgesia.",
    cautions: "Do not administer through same IV line as blood products (esterases inactivate the drug). Always have atropine and glycopyrrolate available for bradycardia, pressors ready for hypotension, and naloxone available for respiratory depression.",
    pearl: "Plan your transition analgesia before stopping the infusion. Because remifentanil wears off so quickly, patients can go from comfortable to severe pain within minutes of discontinuation. Give your long-acting opioid (morphine, hydromorphone) or regional block 20-30 minutes before emergence. Also remember: dose on ideal body weight in obese patients for both boluses and infusions, as clearance correlates better with IBW in severely obese patients.",
  },
  sufentanil: {
    id: "sufentanil",
    name: "Sufentanil",
    class: "Opioid — synthetic piperidine derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Full mu-opioid receptor agonist. 5-10x more potent than fentanyl (10x in balanced anesthesia, 5-7x as primary anesthetic with 100% O₂. Highly lipophilic with rapid CNS penetration.",
    commonUse: "High-dose opioid cardiac anesthesia, major surgical procedures (cardiovascular, neurosurgery), epidural analgesia for labor, cases requiring profound sympathetic blockade.",
    dose: "Highly context-dependent. Analgesic adjunct dosing can range from 1-2 to 2-8 mcg/kg IV depending on length of case. As a primary anesthetic, can be over 8 mcg/kg IV up to 25-30. Consult your institution's formularies and protocols.",
    onset: "IV: 1-3 minutes (distribution time 1.4 min).",
    duration: "Elimination half-life ~164 minutes in adults; shorter in children (97 min), longer in neonates (434 min).",
    sideEffects: "Bradycardia, chest wall rigidity, respiratory depression, hypotension, nausea/vomiting, pruritus, apnea.",
    cautions: "Chest wall rigidity is dose-dependent and more pronounced than fentanyl, so give slowly and have muscle relaxant ready. Glycopyrrolate should be ready for potential bradycardia due to vagotonic effect. Metabolized hepatically, no active metabolites (safer in renal failure than morphine).",
    pearl: "Sufentanil's niche is high-dose opioid cardiac anesthesia where its extreme potency and superior hemodynamic stability shine—at doses of 25-30 mcg/kg, it completely blocks the catecholamine response to sternotomy and cardiopulmonary bypass, maintaining favorable myocardial oxygen balance."
  },
  methadone: {
    id: "methadone",
    name: "Methadone",
    class: "Opioid — synthetic diphenylheptane derivative",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Full mu-opioid receptor agonist, NMDA receptor antagonist, SNRI.",
    commonUse: "Intraoperative analgesia for major surgery (single-dose technique), chronic pain, opioid use disorder maintenance, high-pain procedures.",
    dose: "Intraoperative (single dose): 0.15-0.25 mg/kg IBW at induction. IV (opioid-naïve, pain): 2.5-10 mg every 8-12 hours, titrate slowly.",
    onset: "IV: 10-20 minutes.",
    duration: "Analgesic effect ~8 hours, but remember elimination half-life is 15-60 hours (Paediatric Anesthesia, Boisvert-Plante et al, 2023).",
    sideEffects: "Respiratory depression, chest wall rigidity (rapid large bolus), bradycardia, nausea.",
    cautions: "QTc prolongation is the major concern, approximately 15% of patients develop dose-dependent QTc prolongation (JAMA, Harris et al, 2026). Risk factors: doses >100-150 mg/day, hypokalemia, hypomagnesemia, concomitant QTc-prolonging drugs (haloperidol, fluoroquinolones), baseline QTc >440 ms (men) or >460 ms (women). Many other drug interactions exist.",
    pearl: "The key advantage of intraoperative methadone is its dual mechanism (mu-agonist + NMDA antagonist) combined with its long half-life, providing extended postoperative analgesia from a single induction dose—studies show 0.25 mg/kg IBW reduces total in-hospital opioid use by ~50% compared to short-acting opioids (Anesthesiology, Kharasch et al, 2023).",
  },
  diazepam: {
    id: "diazepam",
    name: "Diazepam",
    class: "Benzodiazepine",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "GABA-A receptor positive allosteric modulator.Enhances GABA binding, increasing chloride conductance and neuronal inhibition.",
    commonUse: "Preoperative anxiolysis, procedural sedation (endoscopy, cardioversion), status epilepticus, acute alcohol withdrawal, muscle spasm.",
    dose: "Procedural sedation: 5-10 mg IV (max 20 mg).",
    onset: "IV: 1-3 minutes; IM: 15-30 minutes (erratic absorption).",
    duration: "Clinical effect 1-2 hours; elimination half-life 20-100 hours (active metabolite desmethyldiazepam extends to 30-200 hours).",
    sideEffects: "Drowsiness, fatigue, ataxia, venous thrombosis/phlebitis at injection site, respiratory depression, hypotension, bradycardia, paradoxical agitation, coughing/laryngospasm (endoscopy).",
    cautions: "Phlebitis is common with IV diazepam, use large veins, avoid hand/wrist veins, never mix with other drugs in syringe. Contains propylene glycol: risk of toxicity with high doses (metabolic acidosis, renal failure).",
    pearl: "The key practical difference from midazolam: diazepam has erratic IM absorption (making IM midazolam far superior for premedication) and causes significant phlebitis at the injection site. This is why midazolam has largely replaced diazepam for intraoperative use. However, diazepam's active metabolite (dismethyldiazepam) with extremely long half-life (up to 200 hours) makes it uniquely valuable for alcohol withdrawal.",
  },
  oxycodone: {
    id: "oxycodone",
    name: "Oxycodone",
    class: "Opioid — semi-synthetic phenanthrene derivative, thebaine-derived",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Full mu-opioid receptor agonist; analgesic effect primarily from parent compound (not metabolites). Metabolized via CYP3A4 (major) to noroxycodone and CYP2D6 (minor) to oxymorphone.",
    commonUse: "Moderate-to-severe postoperative pain (oral step-down from IV opioids), acute pain management, transition analgesia.",
    dose: "Opioid-naïve: 5-15 mg PO every 4-6 hours as needed. IV (perioperative): ~0.06-0.1 mg/kg (when available) (Anesthesia and Analgesia, Yu et al, 2020).",
    onset: "PO: 10-15 minutes; peak effect ~1 hour.",
    duration: "3-6 hours (immediate-release formulations).",
    sideEffects: "Nausea, constipation, vomiting, headache, pruritus, dizziness, somnolence, respiratory depression constipation, vomiting.",
    cautions: "High oral bioavailability (60-87%) compared to other opioids. CYP3A4 inhibitors (azoles, macrolides, ritonavir) increase oxycodone levels; CYP3A4 inducers (rifampin, carbamazepine, phenytoin) decrease levels significantly. Avoid with MAOIs (risk of serotonin syndrome or opioid toxicity).",
    pearl: "For postoperative pain, a Cochrane review found oxycodone 10 mg + acetaminophen 650 mg provides 10 hours of analgesia with an NNT of 2.7, making it an excellent oral combination for discharge prescriptions (Cochrane, Gaskell et al, 2009). Oxycodone is approximately 1.5x more potent than oral morphine (10 mg oxycodone ≈ 15 mg morphine PO).",
  },
  tramadol: {
    id: "tramadol",
    name: "Tramadol",
    class: "Opioid — Atypical synthetic",
    controlled: true,
    schedule: "DEA Schedule IV",
    mechanism: "Weak mu-opioid agonist + serotonin/norepinephrine reuptake inhibitor (SNRI). Active metabolite M1 (O-desmethyltramadol) is 200x more potent at mu-receptors than parent compound.",
    commonUse: "Moderate pain management, multimodal analgesia adjunct, patients where traditional opioids are less desirable (lower addiction/respiratory depression risk) (JAMA Surgery,  Wick et al, 2017).",
    dose: "Dosing is complex and dependent on various clinical criteria. For example, the VA has an entire guideline on best clinical practice for the use of opioids in chronic pain management (2022).",
    onset: "<60 minutes PO.",
    duration: "Peak 2-3 hours; elimination half-life ~6 hours.",
    sideEffects: " Nausea, dizziness, constipation, somnolence, sweating, pruritus, seizures, serotonin syndrome.",
    cautions: "Seizure risk increases with supratherapeutic doses, SSRIs/SNRIs, TCAs, MAOIs, neuroleptics, or history of epilepsy. Serotonin syndrome risk.",
    pearl: "Naloxone only partially reverses tramadol toxicity because of the non-opioid component. You may need benzodiazepines for seizures and cyproheptadine for serotonin syndrome.",
  },
  codeine: {
    id: "codeine",
    name: "Codeine",
    class: "Opioid - natural alkaloid",
    controlled: true,
    schedule: "DEA Schedule II",
    mechanism: "Prodrug. Codeine itself has weak mu-opioid affinity. Requires CYP2D6 conversion to morphine (5-10% of dose) for analgesic effect.",
    commonUse: "Mild-moderate pain, antitussive (largely replaced by safer alternatives).",
    dose: "Adults: 15-60 mg PO q4-6h PRN. Maximum should be 360mg/day, and also make sure to monitor acetaminophen limits if using a combination product.",
    onset: "<60 minutes PO; peak analgesia 2 hours.",
    duration: "4-6 hours; half-life ~2.9 hours.",
    sideEffects: "Nausea, constipation, drowsiness, dizziness, respiratory depression (especially in ultra-rapid metabolizers).",
    cautions: "FDA Black Box Warning: Contraindicated in children <12 years and <18 years post-tonsillectomy/adenoidectomy due to fatal respiratory depression in ultra-rapid CYP2D6 metabolizers. ltra-rapid metabolizers (1-10% Caucasians, >10% in some populations) convert codeine to morphine too quickly, resulting in fatal overdose even at standard doses.",
    pearl: "Codeine is a prodrug with unpredictable efficacy and a dangerous safety profile. Unlike other opioids where 'what you give is what you get,' codeine's analgesic effect depends entirely on CYP2D6 conversion to morphine—meaning ~7% of patients get no pain relief (poor metabolizers) while 1-10% are at risk for fatal overdose (ultra-rapid metabolizers) (Clinical Pharmacology and Therapeutics, Crews et al, 2012).",
  },
  buprenorphine: {
    id: "buprenorphine",
    name: "Buprenorphine",
    class: "Opioid — synthetic",
    controlled: true,
    schedule: "DEA Schedule III",
    mechanism: "Partial mu-opioid agonist (high affinity, low intrinsic efficacy), kappa antagonist, delta antagonist, nociceptin receptor agonist. Binds mu receptor with ~6.7x affinity of fentanyl and ~120x oxycodone, but only partially activates it, producing a ceiling effect on respiratory depression (American Psychiatric Association, Margo et al, 2022).",
    commonUse: "Opioid use disorder (OUD) maintenance, chronic pain, perioperative analgesia in OUD patients.",
    dose: "Dosing for analgesic effect is highly complex and often alongside weaning doses of full agonists. Furthermore, route of administration, from patches, oral tablets, sublingual, or even buccal formuatlions, makes OUD and pain management highly context-dependent.",
    onset: "Sublingual: 30-60 minutes",
    duration: "24-42 hours (sublingual/buccal); slow receptor dissociation provides prolonged effect",
    sideEffects: "Nausea, headache, constipation, sweating, insomnia, precipitated withdrawal (if given too early after full agonist) (JAMA, Harris et al, 2026 + NEJM, Schuckit, 2016).",
    cautions: "Renal impairment increases active metabolite accumulation; histamine release can be hemodynamically relevant.",
    pearl: "Do NOT discontinue buprenorphine before surgery. Current ASRA guidelines recommend continuing buprenorphine at home dose because: (1) adequate analgesia is achievable with multimodal therapy + high-affinity full agonists (fentanyl/hydromorphone), (2) discontinuation carries >50% risk of OUD recurrence or death, and (3) patients maintained on buprenorphine actually have lower PCA requirements than those whose buprenorphine was stopped (Regional Anesthesia and Pain Medicine, Kohan et al, 2021).",
  },
};

/** Supply bin taxonomy (10 items, 2 rows × 5 columns) */
window.PYXIS_SUPPLY_BINS = [
  // Row 1
  { id: "tube-caps",     label: "Tube caps",    row: 1, description: "Red and green tube caps for IV ports and stopcocks. Red = no additive (blood draws), Green = alcohol-based disinfecting cap. This is Yale's color coding, but make sure to know your institution's color coding. You may be asked to fetch caps from supply bins based on their color or context." },
  { id: "tourniquets",   label: "Tourniquets",  row: 1, description: "Used for IV placement. Tighten proximal to intended IV site to engorge veins. For example, if you are aiming to place a PIV in a hand vein, it is appropriate to tie to tourniquet using proper technique at the forearm or above the antecubital fossa. Try not to place the PIV on the same side as the blood pressure cuff. The tourniquet should be released after the IV catheter is threaded into the vein. A detailed PIV placement tutorial is coming soon!" },
  { id: "alcohol-wipes", label: "Alcohol wipes", row: 1, description: "70% isopropyl pads for IV site prep, needle prep, and general antisepsis. Allow to dry before insertion for best effect." },
  { id: "gauze",         label: "Gauze + Saline Flushes",         row: 1, description: "You may find it useful to have a bunch of 4×4 gauze pads for field prep, bleeding control, airway work, and general OR use. Saline flushes are also often useful for pushing/mixing drugs or cleaning things. One way to be helpful in the OR is to help the team apply gauze to patients' wounds and incisions to control bleeding, or use saline flushes with gauze to clean up blood, spills, saliva, tears, or other bodily fluids. Remember, the saline inside the flush is sterile but the syringe itself is NOT!" },
  { id: "tape",          label: "Tape",          row: 1, description: "Multiple types: silk tape for ETT securing, paper tape for wound wrapping, clear Tegaderm-style for A-lines and IVs. Know which tape for which use." },
  // Row 2
  { id: "ecg-stickers",  label: "ECG stickers",  row: 2, description: "5-lead ECG electrode pads (RA, LA, RL, LL, V1 lead). One of the easiest ways you can help out in both the OR and postop is to help the team place ECG lead stickers and monitors on patients. Make sure you place them with full contact and correctly to minimize artifacts! This configuration of 5-leads ECG is known as the Mason-Likar Lead system, meant to reduce motion artifact during continuous monitoring while allowing patient mobility. Specifically, the V1 lead is placed in the 4th intercostal space at the right sternal border, commonly used for arrhythmia monitoring (Circulation, Sandau et al, 2017). Other V-lead placements along the 4th and 5th intercostal spaces across the left side of the chest (think back to our standard 12-lead configuration) are commonly used to monitor myocardial ischemia. When helping set up the patient monitors, remember the mnemonic: clouds over grass, smoke over fire, dirt in between." },
  { id: "oral-airways",  label: "Oral airways",  row: 2, description: "OPAs for maintaining airway in unconscious patients. Size by measuring corner of mouth to earlobe. Do not use in conscious patients as it triggers gag reflex. For patients with difficult airways to unresposive to normal masking, these may be super helpful to keep in mind." },
  { id: "lab-tubes",     label: "Lab tubes",     row: 2, description: "Blood collection tubes: purple top (EDTA → CBC), green top (lithium heparin → BMP), blue top (citrate → coag/PT/INR), gold top (serum separator → type & screen)." },
  { id: "tegaderms",     label: "Tegaderms",     row: 2, description: "Transparent polyurethane film dressing, standard for securing peripheral IVs and central line sites while maintaining visualization of the insertion site. One useful thing you can do in the morning is to help prepare PIV kits, which require TWO tegaderms, one 18G, one 20G needles, alcohol wipes, tourniquets, gauze, saline flush, and IV extension connectors." },
  { id: "nasal-supplies", label: "Nasal / oral adj.", row: 2, description: "Nasal cannulas (2–6 L/min O2), nasal trumpets (lubricate well; relative contraindication in suspected basilar skull fracture), tongue depressors. Know what you're reaching for." },
];

/** Main drug drawer taxonomy */
window.PYXIS_DRAWERS = [
  { id: "induction",   label: "Induction",                    shortLabel: "Induction",   medicationIds: ["propofol", "etomidate", "ketamine", "midazolam"] },
  { id: "paralytics",  label: "Paralytics",                   shortLabel: "Paralytics",  medicationIds: ["rocuronium", "succinylcholine", "vecuronium", "cisatracurium"] },
  { id: "pressors",    label: "Hemodynamic Control",       shortLabel: "Hemodynamics",    medicationIds: ["phenylephrine", "ephedrine", "norepinephrine", "vasopressin", "epinephrine", "metoprolol", "nicardipine", "esmolol", "hydralazine"] },
  { id: "reversal",    label: "Reversal / Rescue",            shortLabel: "Reversal",    medicationIds: ["sugammadex", "neostigmine", "glycopyrrolate", "naloxone", "flumazenil", "diphenhydramine"] },
  { id: "supportive",  label: "Supportive Care", shortLabel: "Supportive",  medicationIds: ["lidocaine", "ondansetron", "dexamethasone", "atropine", "cefazolin", "ketorolac"] },
];

/**
 * Controlled-substance cell mapping (15 cells, 3 rows × 5 cols).
 * null = empty/locked slot.
 */
window.PYXIS_CONTROLLED_CELLS = [
  "fentanyl",     "remifentanil", "hydromorphone", "oxycodone",     "morphine",
  "methadone",    "sufentanil",   "midazolam",     "lorazepam",     "diazepam",
  "tramadol",      "codeine",     "buprenorphine", "meperidine",    "ketamine",
];

/** Left-cabinet specialty drawers */
window.PYXIS_LEFT_DRAWERS = [
  {
    id: "airway",
    label: "Airway",
    shortLabel: "Airway",
    items: [
      { id: "mac-blade",   name: "MAC Blade",           category: "Laryngoscopy",           description: "A Macintosh (Mac) blade is a curved laryngoscope blade used for direct laryngoscopy that is inserted into the vallecula (the space between the base of the tongue and the epiglottis) to indirectly lift the epiglottis and expose the vocal cords for endotracheal intubation. Insertion technique is to bring the patient head to your sternum to optimize visibility of the cords. The blade is inserted into the right side of the mouth, then advanced while sweeping the tongue to the left. The tip is positioned in the vallecula, and the entire blade is lifted upward and forward at a 45-degree angle (in the direction of the handle) to expose the glottis. Insert gently and do NOT lever the blade (called 'rocking') - it neither helps visualize and risks tooth chipping and trauma. Contrast to a Miller blade, which has more of a straight blade meant for anterior larynx, large floppy epiglottis, or limited mouth openings." },
      { id: "ett",         name: "Endotracheal Tube",   category: "Intubation",             description: "An endotracheal tube (ETT) is a flexible plastic tube inserted through the mouth or nose into the trachea to establish a definitive airway for mechanical ventilation, airway protection, and oxygenation in critically ill or anesthetized patients. Key components include the tube body (with centimeter deep markings), angled bevel (at the tip to aid insertion), murphy eye (side hole that allows for alternative airway), cuff (inflatable balloon that seals the airway), and a connector to the ventilator. ETTs are sized by internal diameter in millimeters. Common adult sizes are 7.0-8.0 mm, though the outer diameter varies by manufacturer even with the same ID. Height-based selection is more accurate than sex-based selection: typically 7.0 mm for height ≤160 cm, 7.5 mm for 161-179 cm, and 8.0 mm for ≥180 cm. Pediatric tube sizing is typically age divided by 4 + 4 for uncuffed, + 3.5 for cuffed. Insertion depth is usually the internal diameter number multiplied by 3." },
      { id: "lma",         name: "LMA",                 category: "Supraglottic airway",    description: "LMAs are sized 1-6 based on patient weight. Common adult sizes are size 3 (30-50 kg), size 4 (50-70 kg), and size 5 (>70 kg). However, sex-based selection (size 4 for females, size 5 for males) often provides better seal and less air leak than weight-based selection. Larger sizes generally provide higher oropharyngeal leak pressures and better fiberoptic views. A key consideration is that LMAs do NOT protect against aspiration, so contraindicated in patients with full stomach, emergency surgery, obesity, pregnancy, symptomatic GERD, or hiatal hernia. It's also less suitable for procedures requiring high airway pressures (>20-25 cmH₂O) due to risk of gastric insufflation. Otherwise, key advantages include easy insertion without laryngoscopy, less hemodynamic and airway stimulation, and can be used for both spontaneous and positive pressure ventilation. Classic, ProSeal, i-gel variants available. Image courtesy of NEJM, Lighthall et al, 2013." },
      { id: "glidescope",  name: "GlideScope",          category: "Video laryngoscopy",     description: "Video laryngoscopy is an intubation technique that uses a laryngoscope with a camera at the tip of the blade that displays the airway on a video screen, allowing visualization of the vocal cords without requiring a direct line of sight from the mouth. At Yale, we use the GlideScope, with clear plastic, single-use interchangeable MAC blades. GlideScope is a specific brand of video laryngoscope characterized by its acutely angled (hyperangulated) blade that provides an improved glottic view. We typically use a MAC 3 blade, but sometimes use MAC 4 for bigger adults. Due to hyperangulation, sometimes you may need to sweep the tongue out of the way to advance the blade. As you advance, make sure to visualize the epiglottis and insert the tip of the blade into the vallecula. Other tips and tricks for consistent intubation success with the GlideScope are coming soon!" },
      { id: "bougie",      name: "Bougie",              category: "Difficult airway adjunct", description: "A bougie (also called a tracheal tube introducer or Eschmann stylet) is a long, semi-rigid, flexible guide used to facilitate endotracheal intubation when the glottic opening is difficult to visualize. It serves as a 'railroad track' over which the endotracheal tube can be advanced into the trachea. Indications usually for difficult intubations, which can be objectively graded using the Cormack-Lehane scale (Annals of Emergency Medicine, Latimer et al, 2020). During laryngoscopy, the bougie is advanced with the angled tip pointing anteriorly toward the expected glottic opening. Once inserted, glottic opening.tracheal placement is confirmed by feeling 'tracheal clicks' as the tip bumps along the cartilaginous tracheal rings, and/or 'hold-up' at approximately 28-32 cm when the tip reaches a distal bronchus. The ETT is then railroaded over the bougie with a 90-degree counterclockwise rotation to prevent the tube tip from catching on the arytenoids." },
      { id: "bag-mask",    name: "Bag-Valve Mask",      category: "Emergency ventilation",  description: "Bag-valve-mask ventilation is a manual positive-pressure ventilation technique using a self-inflating bag connected to a face mask to provide oxygenation and ventilation to patients who cannot breathe adequately on their own. Indications include respiratory arrest, cardiac arrest, apnea during RSI, failed intubation, or preoxygenation before definitive airway attempts. You may be asked to perform mask ventilation for preoxygenation in the OR, or occasionally for emergency indications in the ICU/emergency room rotation. Proper technique is called the E-C clamp. It is a one-handed technique where the thumb and index finger form a 'C' shape to create an airtight seal over the nose and mouth, while the remaining three fingers (middle, ring, pinky) form an 'E' shape along the lower edge of the jaw to elevate the mandible and open the airway. This technique simultaneously achieves mask seal and airway patency through jaw thrust/chin lift. OPAs/NPAs may assist in increasing ventilation, and parameters should be adjusted to respiratory rate of 10/min, inspiratory time of 1 second, and tidal volumes of 500~600 mL (NEJM, Casey et al, 2019). Confirm effectiveness by observing symmetric chest rise, breath sounds, and if available, ETCO₂ waveform. Remember, two-person technique has been shown to always be superior to one-person, if available. Image courtesy of NEJM, Shrestha et al, 2021." },
      { id: "afio",    name: "Fiberoptic Intubation",      category: "Difficult airway adjunct",  description: "Fiberoptic intubation (FOI) is a technique using a flexible bronchoscope to visualize the airway in real-time and guide an endotracheal tube into the trachea. It is considered the gold standard for managing anticipated difficult or even threatened airways (e.g. parapharyngeal abscess with worsening trismus, odynophagia, and respiratory symptoms), particularly when performed with the patient awake and spontaneously breathing. It includes a flexible bronchoscope and a pre-loaded endotracheal tube (usually a nasopharyngeal access). The ASA Difficult Airway Algorithm is the key criteria for determining awake vs. asleep intubations. In awake fiberoptic intubations, the patient is kept awake with conscious sedation on low-dose dexmetomidine. The airway is locally anesthesized using lidocaine nebulizers in an 'as-you-go' fashion (be careful with CKD patients for lidocaine). Do NOT put the patient to sleep before you achieve an airway in threatened patients. Oxymetazoline and glycopyrrolate as necessary. Always have video laryngoscopy, LMA, and a surgical (ENT preferred) team present in case you need to do an awake tracheostomy. One way of assessing airway difficulty that you may see in anesthesia pre-op patient interviews is the Mallampati score (see above)." },
    ],
  },
  {
    id: "lines",
    label: "Lines & Infusion",
    shortLabel: "Lines",
    items: [
      { id: "peripheral-iv",  name: "Peripheral IV (PIV)",       category: "Vascular access",      description: "A peripheral intravenous (PIV) catheter is a short, flexible catheter inserted into a superficial vein to provide vascular access for fluid administration, medication delivery, and blood sampling. Gauge guide: 14G (trauma/massive transfusion), 16–18G (standard OR), 20–22G (routine), 22-24G (peds, fragile veins). Larger bore = faster flow (Poiseuille's law: flow ∝ r⁴). Some quick technique tips: stabilize the skin by applying traction near the location of entry; enter the skin with needle at 45 degree angle, but once you see flash, lower your angle and advance the needle SLIGHTLY to ensure it is in the vein, then advance the catheter; they prefer forearm and dorsum of the hand IV in the OR for several reasons: mainly to avoid kinking of the catheter intra-op, especially if the patient is positioned in a non-supine position, and also because it allows for backup options further up the arm if the first site does not succeed. Some common complications include phlebitis, infiltration/extravasation, hematomas, and very rarely, infections. The picture above shows a standard PIV kit that you can make for your Yale residents!"},
      { id: "a-line",         name: "Arterial Line (A-line)",    category: "Invasive monitoring",  description: "An arterial line (A-line) is an indwelling catheter placed in a peripheral artery (most commonly the radial artery) that provides continuous, real-time blood pressure monitoring and easy access for frequent arterial blood gas sampling. You will see this frequently in cardiac rooms or other cases where tight blood pressure control or blood sampling is required. The Modified Allen Test is a simple test to assess collateral flow before A-line insertion. Compress both the radial and ulnar artery while the patient clenches their fist. Release the ulnar artery and assess reperfusion - if achieved within 5-15 seconds, there is adequate collateral flow. Note that recent research has shown that the Modified Allen Test is not a reliable predictor of ischemic complications, and thus an abnormal result should not be used to contraindicate A-line insertion. Especially at Yale, many attendings will advocate for you to use the ultrasound: especially improves first-pass success rates (~71% improvement) and is especially useful in obese, hypotensive, or difficult-access patients. Transducer must be at the level of the phlebostatic axis (4th intercostal space, mid-axillary line) and zeroed to atmospheric pressure. Flush the system with pressurized saline to prevent clotting and air emboli." },
      { id: "cvc",            name: "Central Venous Catheter",   category: "Central access",       description: "Placed in internal jugular, subclavian, or femoral vein. Indications: CVP monitoring, drug infusion, access when peripheral unavailable. Seldinger technique (wire → dilator → catheter). Confirm with CXR post-insertion." },
      { id: "infusion-lines", name: "Infusion Pump Tubing",      category: "IV tubing",            description: "Macrobore tubing for high-flow resuscitation. Microbore for TIVA, vasopressors, and precision delivery. Components: spike (bag piercing), drip chamber (flow visualization), roller clamp (manual flow control), Y-sites (medication injection), luer-lock connectors, and pump cassette segment." },
      { id: "fluid-bags",     name: "Fluid Bags (NS / LR)",      category: "IV fluids",            description: "Normal Saline (0.9% NaCl): isotonic, compatible with blood products, but risks hyperchloremic metabolic acidosis with large volumes. Lactated Ringers: more physiologic electrolyte balance, preferred for surgical resuscitation in many institutions." },
      { id: "infusion-pump",  name: "Infusion Pump",             category: "Equipment",            description: "Infusion pumps are electromechanical devices used to deliver IV medications with precise, controlled flow rates. There are four different types you may see: syringe pumps, large-volume peristaltic pumps, gravity-feeds, and target-controlled infusion pumps. Use pump presets for medication dose and delivery. Common failure modes that you may see is occlusion, disconnection, siphoning, or air emboli. Some clinical considerations include considering 'dead volume,' or the volume of the tubing, start-up delays for achieving steady states, and vertical displacements of tubing or drugs that causes changes in hydrostatic pressure. "},
    ],
  },
];

/** Advising faculty for the clerkship project */
window.ABOUT_FACULTY = [
  // Add advising faculty entries here following the same format:
  // {
  //   id: "faculty-1",
  //   name: "Dr. First Last",
  //   initials: "FL",
  //   color: "#2a5c8a",
  //   title: "Title / Role",
  //   photo: "images/firstname-last.jpg",
  //   bio: "Bio text here.",
  //   email: "email@yale.edu"
  // },

  {
    id: "faculty-1",
    name: "Dr. Viji Kurup",
    initials: "VK",
    color: "#2a5c8a",
    title: "Professor of Anesthesiology",
    photo: "images/vijikurup_thumb.jpg",
    photo_high: "images/vijikurup_high.jpg",
    bio: "Viji Kurup MD is Professor in the Department of Anesthesiology at Yale. Viji completed her Residency in Anesthesiology and Fellowship in Cardiothoracic Anesthesia at Yale. She has been on faculty in the department since 2005 where she has developed a career as a medical educator. She has completed her fellowship in Medical Education and is currently Vice Chair for Medical Education as well as Director of the Yale Anesthesia Media Lab and the Course Director for the Anesthesia Resident Simulations. She has led the integration of the Flipped Classroom model for Anesthesia Resident Training at Yale. Viji's academic interests include participating in Global Health projects and exploring innovative ways of integrating technology in medical education. She is also the Co-Chair for the Global health and outreach committee in the Society for Education in Anesthesia (SEA). She has volunteered with the Health Volunteer Overseas Program (www.hvousa.org) in Vietnam. She enjoys teaching and was awarded the Faculty Award for Excellence in Education and Leadership for the Department of Anesthesiology. She is a firm believer in the importance of physician wellness and has introduced a comprehensive wellness curriculum within her department. She is the Past President of the CT State Society of Anesthesiologists and is actively involved in advocacy efforts both at the State and Federal level. She also volunteers in the community and is a regular speaker at career day for inner city schools in New Haven. She lives in Trumbull CT with her husband and two kids, and because that was clearly not keeping her busy enough, a high-maintenance cat! In her free time, she enjoys cooking, painting (acrylic on canvas), reading and meditating. Dr. Kurup is a key faculty advisor for the Anesthesia Playground website.",
    email: "viji.kurup@yale.edu",
  },
];

/** Medical students on rotation */
window.ABOUT_STUDENTS = [
  // Add student entries here following the same format:
  // {
  //   id: "student-1",
  //   name: "First Last",
  //   initials: "FL",
  //   color: "#0d9488",
  //   title: "MS3 / MS4 — Yale School of Medicine",
  //   photo: "images/firstname-last.jpg",
  //   bio: "Bio text here.",
  //   email: "email@yale.edu"
  // },
  {

    id: "student-1",
    name: "Chanseo (CS) Lee",
    initials: "CL",
    color: "#0d9488",
    title: "Founding Tech Lead (MS3)",
    photo: "images/chanseolee.jpg",
    bio: "Chanseo (CS) is a third-year medical student at the Yale School of Medicine interested in anesthesiology. Previously, he studied at the Massachusetts Institute of Technology. He works on language models in data mining/clincal workflows, deeptech AI product and strategy, and biotech venture capital. He also researches perioperative medicine, clinical AI, and biotechnology at the Yale Cardiothoracic Surgery Outcomes Group and at Harvard/MGH Center for Systems Biology. Now, he is building out the interactive Anesthesia Playground with visionary, academic, and strategic support from Dr. Szabo, Dr. Guzzi, and Dr. Kurup, with the aims of furthering personalized medical education. In his free time, he plays guitar, enjoys breakdancing, playing tennis, and collecting Playbills and movie posters.",
    email: "chanseo.lee@yale.edu"
  },
];

/** Attendings for About Us page */
window.ABOUT_RESIDENTS = [
  {
    id: "resident-1",
    name: "Dr. Justin Anzalone",
    initials: "JA",
    color: "#207a5e",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/justinanzalone.jpg",
    bio: "Originally from Louisiana, Dr. Anzalone completed his undergraduate degree at the University of Louisiana at Lafayette. He continued on the complete a masters of physician assistant studies at New York Institute of Technology, where he practiced for 8 years prior to returning to complete his medical school training at Ross University School of Medicine. Dr. Anzalone and his wife, Yvette, have three beautiful daughters: Alexandra, Caroline, and Annalise. Dr. Anzalone enjoys spending time with family, hiking, gravel cycling, roasting coffee, and traveling.",
    email: "justin.anzalone@yale.edu"
  },
  {
    id: "resident-2",
    name: "Dr. Shriya Tanti",
    initials: "ST",
    color: "#1a7a8a",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/shriyatanti.jpg",
    bio: "Anesthesiology Resident at Yale New Haven Hospital interested in medical education.",
    email: "shriya.tanti@yale.edu"
  },
  {
    id: "resident-3",
    name: "Dr. Kenneth Hanton",
    initials: "KH",
    color: "#8a5a1a",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/kennethhanton.jpg",
    bio: "Hometown: Napa, CA. Interests: traveling around the east coast, cocktail mixology, going to the zoo, pet cat, Mexican food enthusiast",
    email: "kenneth.hanton@yale.edu"
  },
  {
    id: "resident-4",
    name: "Dr. Adriana Perez",
    initials: "AP",
    color: "#4a6b1a",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/adrianaperez.jpg",
    bio: "Anesthesiology Resident at Yale New Haven Hospital interested in medical education.",
    email: "adriana.perez@yale.edu"
  },
  {
    id: "resident-5",
    name: "Dr. Kendra Brown",
    initials: "KB",
    color: "#730000",
    title: "CA-2 Resident (PGY-3)",
    photo: "images/kendrabrown.jpg",
    bio: "Anesthesiology Resident at Yale New Haven Hospital interested in medical education.",
    email: "kendra.brown@yale.edu"
  },
];

window.ABOUT_ATTENDINGS = [
  {
    id: "attending-1",
    name: "Dr. Chris Szabo",
    initials: "CS",
    color: "#286dc0",
    title: "Associate Professor of Anesthesiology",
    photo: "images/christopherszabo_thumb.jpg",
    photo_high: "images/christopherszabo_high.jpg",
    bio: "Dr. Christopher Szabo is Associate Professor of Anesthesiology at Yale New Haven Hospital. He received his medical degree from the University of Connecticut School of Medicine in 2008. Following his Anesthesia residency at Yale University, Dr. Szabo went on to complete both a Critical Care fellowship and a Postdoctoral Fellowship at Columbia University. In 2017, Dr. Szabo joined the Yale University School of Medicine faculty, providing clinical care to patients in the General Section, Cardiothoracic ICU. Dr. Szabo was the first conceptualizer of this interactive anesthesia playground website - he derived inspiration from J.K. Rowling's old websites.",
    email: "christopher.szabo@yale.edu"
  },
  {
    id: "attending-2",
    name: "Dr. John Guzzi",
    initials: "JG",
    color: "#1a6655",
    title: "Assistant Professor of Anesthesiology",
    photo: "images/johnguzzi_thumb.jpg",
    photo_high: "images/johnguzzi_high.jpg",
    bio: "Dr. John Guzzi is an anesthesiologist based in New Haven, CT, with a subspecialty in Critical Care Medicine. He completed his residency and served as Chief Resident in Anesthesiology at Yale-New Haven Medical Center, where he also pursued a fellowship in Critical Care Medicine. Dr. Guzzi graduated from Georgetown University School of Medicine in 2019. His publications include articles in The New England Journal of Medicine, Journal of Clinical Anesthesia, and Anesthesiology. His research interests range from liver transplantation, medical education, to cardiac anesthesia. He is also the Rotation Director for the Advanced Training Period (ATP) Subinternship and Clerkship Site Director for York Street Campus. Dr. Guzzi was the first developer behind the 30-day Anesthesia Curriculum wheel and is currently working on the 20-day curriculum for medical students, CA-1s, and CA-3s.",
    email: "john.guzzi@yale.edu"
  },
];
