-- 027: Canonical medical schools / programs
-- Run in Supabase Dashboard → SQL Editor, then 028_institution_scope.sql, then 029_content_tenancy.sql.
-- Source: US LCME MD + COCA DO (2026 lists), Canadian faculties of medicine,
-- major Caribbean IMGs, and Yale allied programs. 245 rows.
-- Re-runnable: ON CONFLICT (canonical_name) updates aliases/domains.

CREATE TABLE IF NOT EXISTS public.institutions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  canonical_name  text NOT NULL UNIQUE,
  short_name      text,
  kind            text NOT NULL CHECK (kind IN ('md', 'do', 'canada_md', 'caribbean', 'allied')),
  country         text NOT NULL DEFAULT 'US',
  region          text,
  aliases         text[] NOT NULL DEFAULT '{}',
  email_domains   text[] NOT NULL DEFAULT '{}',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_institutions_short_name
  ON public.institutions (lower(short_name));

CREATE INDEX IF NOT EXISTS idx_institutions_aliases
  ON public.institutions USING gin (aliases);

ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "institutions are publicly readable" ON public.institutions;
CREATE POLICY "institutions are publicly readable"
  ON public.institutions FOR SELECT
  USING (true);

GRANT SELECT ON public.institutions TO anon, authenticated;

INSERT INTO public.institutions
  (canonical_name, short_name, kind, country, region, aliases, email_domains)
VALUES
  ('A.T. Still University of Health Sciences Kirksville College of Osteopathic Medicine', NULL, 'do', 'US', 'Missouri', ARRAY['KCOM','ATSU-KCOM','Kirksville College of Osteopathic Medicine','A.T. Still University of Health Sciences Kirksville']::text[], '{}'::text[]),
  ('A.T. Still University School of Osteopathic Medicine', NULL, 'do', 'US', 'Arizona', ARRAY['ATSU-SOMA','AT Still SOMA','A.T. Still University','School of Osteopathic Medicine in Arizona']::text[], '{}'::text[]),
  ('Alabama College of Osteopathic Medicine', NULL, 'do', 'US', 'Alabama', '{}'::text[], '{}'::text[]),
  ('Albany Medical College', NULL, 'md', 'US', 'New York', '{}'::text[], '{}'::text[]),
  ('Albert Einstein College of Medicine', 'Einstein', 'md', 'US', 'New York', ARRAY['Einstein','Albert Einstein']::text[], ARRAY['einsteinmed.edu']::text[]),
  ('Alice L. Walton School of Medicine', NULL, 'md', 'US', 'Arkansas', ARRAY['Alice L. Walton']::text[], '{}'::text[]),
  ('American University of Antigua College of Medicine', NULL, 'caribbean', 'AG', 'Antigua and Barbuda', ARRAY['American University of Antigua']::text[], '{}'::text[]),
  ('American University of the Caribbean School of Medicine', 'AUC', 'caribbean', 'SX', 'Sint Maarten', ARRAY['AUC','AUC School of Medicine','American University of the Caribbean']::text[], ARRAY['aucmed.edu']::text[]),
  ('Anne Burnett Marion School of Medicine at Texas Christian University', NULL, 'md', 'US', 'Texas', '{}'::text[], '{}'::text[]),
  ('Arizona College of Osteopathic Medicine of Midwestern University', NULL, 'do', 'US', 'Arizona', '{}'::text[], '{}'::text[]),
  ('Arkansas College of Osteopathic Medicine', NULL, 'do', 'US', 'Arkansas', '{}'::text[], '{}'::text[]),
  ('ASU John Shufeldt School of Medicine and Medical Engineering', NULL, 'md', 'US', 'Arizona', ARRAY['ASU John Shufeldt']::text[], '{}'::text[]),
  ('Baptist Health Sciences University College of Osteopathic Medicine', NULL, 'do', 'US', 'Tennessee', ARRAY['Baptist Health Sciences University']::text[], '{}'::text[]),
  ('Baylor College of Medicine School of Medicine', 'Baylor', 'md', 'US', 'Texas', ARRAY['BCM','Baylor','Baylor College of Medicine']::text[], ARRAY['bcm.edu']::text[]),
  ('Boonshoft School of Medicine at Wright State University', NULL, 'md', 'US', 'Ohio', '{}'::text[], '{}'::text[]),
  ('Boston University Aram V. Chobanian & Edward Avedisian School of Medicine', 'Boston University', 'md', 'US', 'Massachusetts', ARRAY['BUSM','Boston University','BU School of Medicine','Boston University School of Medicine','Boston University Aram V. Chobanian & Edward Avedisian']::text[], ARRAY['bu.edu']::text[]),
  ('Burrell College of Osteopathic Medicine', NULL, 'do', 'US', 'New Mexico', '{}'::text[], '{}'::text[]),
  ('California Health Sciences University College of Osteopathic Medicine', NULL, 'do', 'US', 'California', ARRAY['California Health Sciences University']::text[], '{}'::text[]),
  ('California Northstate University College of Medicine', NULL, 'md', 'US', 'California', ARRAY['California Northstate University']::text[], '{}'::text[]),
  ('California University of Science and Medicine', NULL, 'md', 'US', 'California', '{}'::text[], '{}'::text[]),
  ('Campbell University Jerry M. Wallace School of Osteopathic Medicine', NULL, 'do', 'US', 'North Carolina', ARRAY['Campbell University Jerry M. Wallace']::text[], '{}'::text[]),
  ('Carle Illinois College of Medicine', NULL, 'md', 'US', 'Illinois', ARRAY['Carle Illinois']::text[], '{}'::text[]),
  ('Case Western Reserve University School of Medicine', NULL, 'md', 'US', 'Ohio', ARRAY['Case Western Reserve University']::text[], ARRAY['case.edu']::text[]),
  ('Charles E. Schmidt College of Medicine at Florida Atlantic University', NULL, 'md', 'US', 'Florida', '{}'::text[], '{}'::text[]),
  ('Charles R. Drew University of Medicine and Science College of Medicine', NULL, 'md', 'US', 'California', ARRAY['Charles R. Drew University of Medicine and Science']::text[], '{}'::text[]),
  ('Chicago College of Osteopathic Medicine of Midwestern University', NULL, 'do', 'US', 'Illinois', '{}'::text[], '{}'::text[]),
  ('Chicago Medical School of Rosalind Franklin University of Medicine and Science', NULL, 'md', 'US', 'Illinois', '{}'::text[], '{}'::text[]),
  ('Columbia University Vagelos College of Physicians and Surgeons', 'Columbia', 'md', 'US', 'New York', ARRAY['P&S','Columbia','Columbia P&S','Columbia VP&S','Columbia University College of Physicians and Surgeons']::text[], ARRAY['cumc.columbia.edu','columbia.edu']::text[]),
  ('Cooper Medical School of Rowan University', NULL, 'md', 'US', 'New Jersey', '{}'::text[], '{}'::text[]),
  ('Covenant HealthCare College of Medicine at Central Michigan University', NULL, 'md', 'US', 'Michigan', '{}'::text[], '{}'::text[]),
  ('Creighton University School of Medicine', NULL, 'md', 'US', 'Nebraska', ARRAY['Creighton University']::text[], '{}'::text[]),
  ('CUNY School of Medicine', NULL, 'md', 'US', 'New York', '{}'::text[], '{}'::text[]),
  ('Dalhousie University Faculty of Medicine', NULL, 'canada_md', 'CA', 'Nova Scotia', ARRAY['Dalhousie University']::text[], '{}'::text[]),
  ('David Geffen School of Medicine at UCLA', 'UCLA', 'md', 'US', 'California', ARRAY['UCLA','DGSOM','UCLA School of Medicine','David Geffen School of Medicine','University of California Los Angeles School of Medicine','University of California, Los Angeles School of Medicine']::text[], ARRAY['mednet.ucla.edu','ucla.edu']::text[]),
  ('Dell Medical School at The University of Texas at Austin', NULL, 'md', 'US', 'Texas', '{}'::text[], '{}'::text[]),
  ('Des Moines University College of Osteopathic Medicine', NULL, 'do', 'US', 'Iowa', ARRAY['Des Moines University']::text[], '{}'::text[]),
  ('Donald and Barbara Zucker School of Medicine at Hofstra/Northwell', NULL, 'md', 'US', 'New York', '{}'::text[], '{}'::text[]),
  ('Drexel University College of Medicine', NULL, 'md', 'US', 'Pennsylvania', ARRAY['Drexel University']::text[], '{}'::text[]),
  ('Duke University School of Medicine', 'Duke', 'md', 'US', 'North Carolina', ARRAY['Duke','Duke University']::text[], ARRAY['duke.edu']::text[]),
  ('Duquesne University College of Osteopathic Medicine', NULL, 'do', 'US', 'Pennsylvania', ARRAY['Duquesne University']::text[], '{}'::text[]),
  ('D’Youville University College of Osteopathic Medicine', NULL, 'do', 'US', 'New York', ARRAY['D’Youville University']::text[], '{}'::text[]),
  ('East Tennessee State University James H. Quillen College of Medicine', NULL, 'md', 'US', 'Tennessee', ARRAY['East Tennessee State University James H. Quillen']::text[], '{}'::text[]),
  ('Eastern Virginia Medical School at Old Dominion University', NULL, 'md', 'US', 'Virginia', '{}'::text[], '{}'::text[]),
  ('Edward Via College of Osteopathic Medicine', NULL, 'do', 'US', 'Virginia', ARRAY['VCOM']::text[], '{}'::text[]),
  ('Emory University School of Medicine', NULL, 'md', 'US', 'Georgia', ARRAY['Emory University']::text[], ARRAY['emory.edu']::text[]),
  ('Florida International University Herbert Wertheim College of Medicine', NULL, 'md', 'US', 'Florida', ARRAY['Florida International University Herbert Wertheim']::text[], '{}'::text[]),
  ('Florida State University College of Medicine', NULL, 'md', 'US', 'Florida', ARRAY['Florida State University']::text[], '{}'::text[]),
  ('Frank H. Netter M.D. School of Medicine at Quinnipiac University', NULL, 'md', 'US', 'Connecticut', '{}'::text[], '{}'::text[]),
  ('Frederick P. Whiddon College of Medicine at the University of South Alabama', NULL, 'md', 'US', 'Alabama', ARRAY['USA College of Medicine','Whiddon College of Medicine','University of South Alabama College of Medicine']::text[], '{}'::text[]),
  ('Geisel School of Medicine at Dartmouth', 'Dartmouth', 'md', 'US', 'New Hampshire', ARRAY['Geisel','Dartmouth','Dartmouth Medical School']::text[], ARRAY['dartmouth.edu','hitchcock.org']::text[]),
  ('Geisinger Commonwealth School of Medicine', NULL, 'md', 'US', 'Pennsylvania', ARRAY['Geisinger Commonwealth']::text[], '{}'::text[]),
  ('George Washington University School of Medicine and Health Sciences', NULL, 'md', 'US', 'DC', ARRAY['GW SMHS','GWU School of Medicine','George Washington University','George Washington University Medical School']::text[], ARRAY['gwu.edu']::text[]),
  ('Georgetown University School of Medicine', NULL, 'md', 'US', 'DC', ARRAY['Georgetown University']::text[], ARRAY['georgetown.edu']::text[]),
  ('Hackensack Meridian School of Medicine', NULL, 'md', 'US', 'New Jersey', ARRAY['Hackensack Meridian']::text[], '{}'::text[]),
  ('Harvard Medical School', 'Harvard', 'md', 'US', 'Massachusetts', ARRAY['HMS','Harvard','Harvard Med']::text[], ARRAY['hms.harvard.edu','harvard.edu']::text[]),
  ('Howard University College of Medicine', NULL, 'md', 'US', 'DC', ARRAY['Howard University']::text[], ARRAY['howard.edu']::text[]),
  ('Icahn School of Medicine at Mount Sinai', 'Mount Sinai', 'md', 'US', 'New York', ARRAY['ISMMS','Mount Sinai','Mount Sinai School of Medicine']::text[], ARRAY['mssm.edu','mountsinai.org']::text[]),
  ('Idaho College of Osteopathic Medicine', NULL, 'do', 'US', 'Idaho', '{}'::text[], '{}'::text[]),
  ('Illinois College of Osteopathic Medicine', NULL, 'do', 'US', 'Illinois', '{}'::text[], '{}'::text[]),
  ('Indiana University of Pennsylvania College of Osteopathic Medicine', NULL, 'do', 'US', 'Pennsylvania', ARRAY['Indiana University of Pennsylvania']::text[], '{}'::text[]),
  ('Indiana University School of Medicine', NULL, 'md', 'US', 'Indiana', ARRAY['Indiana University']::text[], '{}'::text[]),
  ('Jacobs School of Medicine and Biomedical Sciences, University at Buffalo', NULL, 'md', 'US', 'New York', ARRAY['Jacobs School of Medicine and Biomedical Sciences University at Buffalo']::text[], '{}'::text[]),
  ('Johns Hopkins University School of Medicine', 'Johns Hopkins', 'md', 'US', 'Maryland', ARRAY['JHUSOM','Hopkins','Johns Hopkins','Johns Hopkins University']::text[], ARRAY['jhmi.edu','jhu.edu']::text[]),
  ('Kaiser Permanente Bernard J. Tyson School of Medicine', NULL, 'md', 'US', 'California', ARRAY['Kaiser Permanente Bernard J. Tyson']::text[], ARRAY['kp.org']::text[]),
  ('Kansas City University College of Osteopathic Medicine', NULL, 'do', 'US', 'Kansas', ARRAY['Kansas City University']::text[], '{}'::text[]),
  ('Kansas College of Osteopathic Medicine', NULL, 'do', 'US', 'Kansas', '{}'::text[], '{}'::text[]),
  ('Keck School of Medicine of University of Southern California', 'USC Keck', 'md', 'US', 'California', ARRAY['Keck','USC Keck','USC School of Medicine','University of Southern California School of Medicine']::text[], ARRAY['usc.edu']::text[]),
  ('Kirk Kerkorian School of Medicine at UNLV', NULL, 'md', 'US', 'Nevada', '{}'::text[], '{}'::text[]),
  ('Lake Erie College of Osteopathic Medicine', NULL, 'do', 'US', 'Pennsylvania', ARRAY['LECOM']::text[], '{}'::text[]),
  ('Lewis Katz School of Medicine, Temple University', NULL, 'md', 'US', 'Pennsylvania', ARRAY['Lewis Katz School of Medicine Temple University']::text[], '{}'::text[]),
  ('Liberty University College of Osteopathic Medicine', NULL, 'do', 'US', 'Virginia', ARRAY['Liberty University']::text[], '{}'::text[]),
  ('Lincoln Memorial University DeBusk College of Osteopathic Medicine', NULL, 'do', 'US', 'Tennessee', ARRAY['Lincoln Memorial University DeBusk']::text[], '{}'::text[]),
  ('Loma Linda University School of Medicine', NULL, 'md', 'US', 'California', ARRAY['Loma Linda University']::text[], ARRAY['llu.edu']::text[]),
  ('Louisiana State University School of Medicine in New Orleans', NULL, 'md', 'US', 'Louisiana', '{}'::text[], ARRAY['lsuhsc.edu']::text[]),
  ('Louisiana State University School of Medicine in Shreveport', NULL, 'md', 'US', 'Louisiana', '{}'::text[], '{}'::text[]),
  ('Loyola University Chicago Stritch School of Medicine', NULL, 'md', 'US', 'Illinois', ARRAY['Loyola University Chicago Stritch']::text[], '{}'::text[]),
  ('Marian University College of Osteopathic Medicine', NULL, 'do', 'US', 'Indiana', ARRAY['Marian University']::text[], '{}'::text[]),
  ('Marshall University Joan C. Edwards School of Medicine', NULL, 'md', 'US', 'West Virginia', ARRAY['Marshall University Joan C. Edwards']::text[], '{}'::text[]),
  ('Mayo Clinic Alix School of Medicine', 'Mayo', 'md', 'US', 'Minnesota', ARRAY['Mayo','Mayo Clinic Alix','Mayo Medical School','Mayo Clinic School of Medicine']::text[], ARRAY['mayo.edu']::text[]),
  ('McGill University Faculty of Medicine and Health Sciences', NULL, 'canada_md', 'CA', 'Quebec', ARRAY['McGill Medicine','McGill University']::text[], ARRAY['mcgill.ca']::text[]),
  ('McGovern Medical School at UTHealth Houston', 'McGovern', 'md', 'US', 'Texas', ARRAY['McGovern','UTHealth','UT Houston','McGovern Medical School','UTHealth John P. and Katherine G. McGovern Medical School']::text[], ARRAY['uth.tmc.edu']::text[]),
  ('McMaster University Michael G. DeGroote School of Medicine', NULL, 'canada_md', 'CA', 'Ontario', ARRAY['McMaster University Michael G. DeGroote']::text[], ARRAY['mcmaster.ca']::text[]),
  ('Medical College of Georgia at Augusta University', NULL, 'md', 'US', 'Georgia', '{}'::text[], '{}'::text[]),
  ('Medical College of Wisconsin', NULL, 'md', 'US', 'Wisconsin', '{}'::text[], '{}'::text[]),
  ('Medical University of South Carolina College of Medicine', NULL, 'md', 'US', 'South Carolina', ARRAY['Medical University of South Carolina']::text[], '{}'::text[]),
  ('Medical University of the Americas', NULL, 'caribbean', 'KN', 'Nevis', '{}'::text[], '{}'::text[]),
  ('Meharry Medical College School of Medicine', NULL, 'md', 'US', 'Tennessee', ARRAY['Meharry Medical College']::text[], ARRAY['mmc.edu']::text[]),
  ('Memorial University of Newfoundland Faculty of Medicine', NULL, 'canada_md', 'CA', 'Newfoundland and Labrador', ARRAY['Memorial University of Newfoundland']::text[], '{}'::text[]),
  ('Mercer University School of Medicine', NULL, 'md', 'US', 'Georgia', ARRAY['Mercer University']::text[], '{}'::text[]),
  ('Meritus School of Osteopathic Medicine', NULL, 'do', 'US', 'Maryland', '{}'::text[], '{}'::text[]),
  ('Methodist University Cape Fear Valley Health School of Medicine', NULL, 'md', 'US', 'North Carolina', ARRAY['Methodist University Cape Fear Valley Health']::text[], '{}'::text[]),
  ('Michigan State University College of Human Medicine', NULL, 'md', 'US', 'Michigan', '{}'::text[], '{}'::text[]),
  ('Michigan State University College of Osteopathic Medicine', NULL, 'do', 'US', 'Michigan', ARRAY['MSUCOM','Michigan State University']::text[], '{}'::text[]),
  ('Morehouse School of Medicine', NULL, 'md', 'US', 'Georgia', '{}'::text[], ARRAY['msm.edu']::text[]),
  ('New York Institute of Technology College of Osteopathic Medicine', NULL, 'do', 'US', 'New York', ARRAY['NYITCOM','New York Institute of Technology']::text[], '{}'::text[]),
  ('New York Medical College', NULL, 'md', 'US', 'New York', '{}'::text[], '{}'::text[]),
  ('Noorda College of Osteopathic Medicine', NULL, 'do', 'US', 'Utah', '{}'::text[], '{}'::text[]),
  ('Northeast Ohio Medical University College of Medicine', NULL, 'md', 'US', 'Ohio', ARRAY['Northeast Ohio Medical University']::text[], '{}'::text[]),
  ('Northwestern University Feinberg School of Medicine', 'Northwestern', 'md', 'US', 'Illinois', ARRAY['Feinberg','Northwestern','Northwestern Med','Northwestern University Feinberg']::text[], ARRAY['northwestern.edu','nm.org']::text[]),
  ('NOSM University', 'NOSM', 'canada_md', 'CA', 'Ontario', ARRAY['NOSM','Northern Ontario School of Medicine']::text[], '{}'::text[]),
  ('Nova Southeastern University College of Osteopathic Medicine', NULL, 'do', 'US', 'Florida', ARRAY['Nova Southeastern University']::text[], '{}'::text[]),
  ('Nova Southeastern University Dr Kiran C. Patel College of Allopathic Medicine', NULL, 'md', 'US', 'Florida', ARRAY['Nova Southeastern University Dr Kiran C. Patel']::text[], '{}'::text[]),
  ('NYU Grossman Long Island School of Medicine', NULL, 'md', 'US', 'New York', ARRAY['NYU Grossman Long Island']::text[], '{}'::text[]),
  ('NYU Grossman School of Medicine', 'NYU', 'md', 'US', 'New York', ARRAY['NYU','NYU Med','NYU Grossman','NYU School of Medicine']::text[], ARRAY['nyulangone.org','nyu.edu']::text[]),
  ('Oakland University William Beaumont School of Medicine', NULL, 'md', 'US', 'Michigan', ARRAY['Oakland University William Beaumont']::text[], '{}'::text[]),
  ('Ohio University Heritage College of Osteopathic Medicine', NULL, 'do', 'US', 'Ohio', ARRAY['Ohio University Heritage']::text[], '{}'::text[]),
  ('Oklahoma State University Center for Health Sciences College of Osteopathic Medicine', NULL, 'do', 'US', 'Oklahoma', ARRAY['Oklahoma State University Center for Health Sciences']::text[], '{}'::text[]),
  ('Oregon Health & Science University School of Medicine', NULL, 'md', 'US', 'Oregon', ARRAY['Oregon Health & Science University']::text[], ARRAY['ohsu.edu']::text[]),
  ('Orlando College of Osteopathic Medicine', NULL, 'do', 'US', 'Florida', '{}'::text[], '{}'::text[]),
  ('Pacific Northwest University of Health Sciences College of Osteopathic Medicine', NULL, 'do', 'US', 'Washington', ARRAY['Pacific Northwest University of Health Sciences']::text[], '{}'::text[]),
  ('Paul L. Foster School of Medicine Texas Tech University Health Sciences Center', NULL, 'md', 'US', 'Texas', '{}'::text[], '{}'::text[]),
  ('PCOM South Georgia', NULL, 'do', 'US', 'Georgia', '{}'::text[], '{}'::text[]),
  ('Penn State University College of Medicine', NULL, 'md', 'US', 'Pennsylvania', ARRAY['Penn State University']::text[], '{}'::text[]),
  ('Perelman School of Medicine at the University of Pennsylvania', 'Penn', 'md', 'US', 'Pennsylvania', ARRAY['Penn','UPenn','Penn Med','Perelman','University of Pennsylvania School of Medicine']::text[], ARRAY['pennmedicine.upenn.edu','upenn.edu']::text[]),
  ('Philadelphia College of Osteopathic Medicine', NULL, 'do', 'US', 'Pennsylvania', ARRAY['PCOM','Philadelphia']::text[], '{}'::text[]),
  ('Ponce Health Sciences University School of Medicine', NULL, 'md', 'US', 'Puerto Rico', ARRAY['Ponce Health Sciences University']::text[], '{}'::text[]),
  ('Queen''s University School of Medicine', NULL, 'canada_md', 'CA', 'Ontario', ARRAY['Queen''s University']::text[], '{}'::text[]),
  ('Renaissance School of Medicine at Stony Brook University', NULL, 'md', 'US', 'New York', '{}'::text[], '{}'::text[]),
  ('Robert Larner, M.D. College of Medicine at the University of Vermont', NULL, 'md', 'US', 'Vermont', ARRAY['Robert Larner M.D. College of Medicine at the University of Vermont']::text[], '{}'::text[]),
  ('Rocky Vista University College of Osteopathic Medicine', NULL, 'do', 'US', 'Colorado', ARRAY['Rocky Vista University']::text[], '{}'::text[]),
  ('Rocky Vista University Montana College of Osteopathic Medicine', NULL, 'do', 'US', 'Montana', ARRAY['Rocky Vista University Montana']::text[], '{}'::text[]),
  ('Roseman University College of Medicine', NULL, 'md', 'US', 'Nevada', ARRAY['Roseman University']::text[], '{}'::text[]),
  ('Ross University School of Medicine', 'Ross', 'caribbean', 'BB', 'Barbados', ARRAY['Ross','RUSM','Ross Med','Ross University']::text[], ARRAY['rossu.edu']::text[]),
  ('Rowan University School of Osteopathic Medicine', NULL, 'do', 'US', 'New Jersey', ARRAY['Rowan University']::text[], '{}'::text[]),
  ('Rush Medical College of Rush University Medical Center', NULL, 'md', 'US', 'Illinois', '{}'::text[], '{}'::text[]),
  ('Rutgers New Jersey Medical School', NULL, 'md', 'US', 'New Jersey', ARRAY['Rutgers New Jersey']::text[], '{}'::text[]),
  ('Rutgers Robert Wood Johnson Medical School', NULL, 'md', 'US', 'New Jersey', ARRAY['Rutgers Robert Wood Johnson']::text[], '{}'::text[]),
  ('Saba University School of Medicine', NULL, 'caribbean', 'BQ', 'Saba', ARRAY['Saba University']::text[], '{}'::text[]),
  ('Saint Louis University School of Medicine', NULL, 'md', 'US', 'Missouri', ARRAY['Saint Louis University']::text[], '{}'::text[]),
  ('Sam Houston State University College of Osteopathic Medicine', NULL, 'do', 'US', 'Texas', ARRAY['Sam Houston State University']::text[], '{}'::text[]),
  ('San Juan Bautista School of Medicine', NULL, 'md', 'US', 'Puerto Rico', ARRAY['San Juan Bautista']::text[], '{}'::text[]),
  ('Sidney Kimmel Medical College at Thomas Jefferson University', NULL, 'md', 'US', 'Pennsylvania', '{}'::text[], '{}'::text[]),
  ('Southern Illinois University School of Medicine', NULL, 'md', 'US', 'Illinois', ARRAY['Southern Illinois University']::text[], '{}'::text[]),
  ('Spencer Fox Eccles School of Medicine at the University of Utah', NULL, 'md', 'US', 'Utah', '{}'::text[], ARRAY['utah.edu']::text[]),
  ('St. George''s University School of Medicine', 'SGU', 'caribbean', 'GD', 'Grenada', ARRAY['SGU','St Georges University','St. George''s University','Saint George''s University School of Medicine']::text[], ARRAY['sgu.edu']::text[]),
  ('St. Matthew''s University School of Medicine', NULL, 'caribbean', 'KY', 'Cayman Islands', ARRAY['St. Matthew''s University']::text[], '{}'::text[]),
  ('Stanford University School of Medicine', 'Stanford', 'md', 'US', 'California', ARRAY['Stanford','Stanford Med','Stanford SOM','Stanford University']::text[], ARRAY['stanford.edu']::text[]),
  ('State University of New York Upstate Medical University Alan and Marlene Norton College of Medicine', NULL, 'md', 'US', 'New York', ARRAY['State University of New York Upstate Medical University Alan and Marlene Norton']::text[], '{}'::text[]),
  ('SUNY Downstate Health Sciences University College of Medicine', NULL, 'md', 'US', 'New York', ARRAY['SUNY Downstate Health Sciences University']::text[], '{}'::text[]),
  ('Texas A&M University Naresh K. Vashisht College of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['Texas A&M University Naresh K. Vashisht']::text[], '{}'::text[]),
  ('Texas Tech University Health Sciences Center School of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['Texas Tech University Health Sciences Center']::text[], '{}'::text[]),
  ('The Brody School of Medicine at East Carolina University', NULL, 'md', 'US', 'North Carolina', ARRAY['Brody School of Medicine at East Carolina University']::text[], '{}'::text[]),
  ('The Ohio State University College of Medicine', NULL, 'md', 'US', 'Ohio', ARRAY['The Ohio State University','Ohio State University College of Medicine']::text[], ARRAY['osu.edu','osumc.edu']::text[]),
  ('The University of Arizona College of Medicine Phoenix', NULL, 'md', 'US', 'Arizona', ARRAY['UA COM Phoenix','University of Arizona College of Medicine Phoenix']::text[], ARRAY['arizona.edu']::text[]),
  ('The University of Georgia School of Medicine in Athens', NULL, 'md', 'US', 'Georgia', ARRAY['University of Georgia School of Medicine in Athens']::text[], '{}'::text[]),
  ('The University of Texas at San Antonio Joe R. and Teresa Lozano Long School of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['The University of Texas at San Antonio Joe R. and Teresa Lozano Long','University of Texas at San Antonio Joe R. and Teresa Lozano Long School of Medicine']::text[], '{}'::text[]),
  ('The University of Texas at Tyler School of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['The University of Texas at Tyler','University of Texas at Tyler School of Medicine']::text[], '{}'::text[]),
  ('The Valley College of Osteopathic Medicine', NULL, 'do', 'US', 'Arizona', ARRAY['Valley College of Osteopathic Medicine']::text[], '{}'::text[]),
  ('The Warren Alpert Medical School at Brown University', 'Brown', 'md', 'US', 'Rhode Island', ARRAY['Brown','Brown Medical School','Alpert Medical School','Warren Alpert Medical School','Warren Alpert Medical School at Brown University']::text[], ARRAY['brown.edu']::text[]),
  ('Thomas F. Frist, Jr. College of Medicine at Belmont University', NULL, 'md', 'US', 'Tennessee', ARRAY['Thomas F. Frist Jr. College of Medicine at Belmont University']::text[], '{}'::text[]),
  ('Toronto Metropolitan University School of Medicine', NULL, 'canada_md', 'CA', 'Ontario', ARRAY['Toronto Metropolitan University']::text[], '{}'::text[]),
  ('Touro College of Osteopathic Medicine', NULL, 'do', 'US', 'New York', '{}'::text[], '{}'::text[]),
  ('Touro University College of Osteopathic Medicine', NULL, 'do', 'US', 'California', ARRAY['Touro University']::text[], '{}'::text[]),
  ('Touro University Nevada College of Osteopathic Medicine', NULL, 'do', 'US', 'Nevada', ARRAY['Touro University Nevada']::text[], '{}'::text[]),
  ('Trinity School of Medicine', NULL, 'caribbean', 'VC', 'Saint Vincent and the Grenadines', '{}'::text[], '{}'::text[]),
  ('Tufts University School of Medicine', NULL, 'md', 'US', 'Massachusetts', ARRAY['Tufts University']::text[], ARRAY['tufts.edu']::text[]),
  ('Tulane University School of Medicine', NULL, 'md', 'US', 'Louisiana', ARRAY['Tulane University']::text[], ARRAY['tulane.edu']::text[]),
  ('Uniformed Services University of the Health Sciences F. Edward Hebert School of Medicine', NULL, 'md', 'US', 'Maryland', ARRAY['Uniformed Services University of the Health Sciences F. Edward Hebert']::text[], '{}'::text[]),
  ('Universidad Central del Caribe School of Medicine', NULL, 'md', 'US', 'Puerto Rico', ARRAY['Universidad Central del Caribe']::text[], '{}'::text[]),
  ('University of Alabama at Birmingham Marnix E. Heersink School of Medicine', NULL, 'md', 'US', 'Alabama', ARRAY['UAB','Heersink','UAB School of Medicine','University of Alabama School of Medicine','University of Alabama at Birmingham Marnix E. Heersink']::text[], ARRAY['uab.edu']::text[]),
  ('University of Alberta Faculty of Medicine and Dentistry', NULL, 'canada_md', 'CA', 'Alberta', ARRAY['University of Alberta']::text[], '{}'::text[]),
  ('University of Arizona College of Medicine – Tucson', NULL, 'md', 'US', 'Arizona', ARRAY['UA COM Tucson','University of Arizona College of Medicine Tucson','University of Arizona College of Medicine-Tucson']::text[], ARRAY['arizona.edu']::text[]),
  ('University of Arkansas for Medical Sciences College of Medicine', NULL, 'md', 'US', 'Arkansas', ARRAY['University of Arkansas for Medical Sciences']::text[], '{}'::text[]),
  ('University of British Columbia Faculty of Medicine', NULL, 'canada_md', 'CA', 'British Columbia', ARRAY['University of British Columbia']::text[], ARRAY['ubc.ca']::text[]),
  ('University of Calgary Cumming School of Medicine', NULL, 'canada_md', 'CA', 'Alberta', ARRAY['University of Calgary Cumming']::text[], '{}'::text[]),
  ('University of California, Davis School of Medicine', 'UC Davis', 'md', 'US', 'California', ARRAY['UC Davis','University of California, Davis','University of California Davis School of Medicine']::text[], ARRAY['ucdavis.edu']::text[]),
  ('University of California, Irvine School of Medicine', 'UC Irvine', 'md', 'US', 'California', ARRAY['UC Irvine','University of California, Irvine','University of California Irvine School of Medicine']::text[], ARRAY['uci.edu']::text[]),
  ('University of California, Riverside School of Medicine', 'UC Riverside', 'md', 'US', 'California', ARRAY['UC Riverside','University of California, Riverside','University of California Riverside School of Medicine']::text[], ARRAY['ucr.edu']::text[]),
  ('University of California, San Diego School of Medicine', 'UCSD', 'md', 'US', 'California', ARRAY['UCSD','UC San Diego','UC San Diego School of Medicine','University of California, San Diego','University of California San Diego School of Medicine']::text[], ARRAY['ucsd.edu','health.ucsd.edu']::text[]),
  ('University of California, San Francisco School of Medicine', 'UCSF', 'md', 'US', 'California', ARRAY['UCSF','UCSF SOM','UC San Francisco','UCSF Medical School','UCSF School of Medicine','San Francisco School of Medicine','UC San Francisco School of Medicine','University of California San Francisco','University of California, San Francisco','University of California San Francisco School of Medicine']::text[], ARRAY['ucsf.edu']::text[]),
  ('University of Central Florida College of Medicine', NULL, 'md', 'US', 'Florida', ARRAY['University of Central Florida']::text[], '{}'::text[]),
  ('University of Chicago Division of the Biological Sciences The Pritzker School of Medicine', 'Pritzker', 'md', 'US', 'Illinois', ARRAY['Pritzker','UChicago Pritzker','University of Chicago Pritzker School of Medicine','University of Chicago Division of the Biological Sciences The Pritzker']::text[], ARRAY['uchicago.edu']::text[]),
  ('University of Cincinnati College of Medicine', NULL, 'md', 'US', 'Ohio', ARRAY['University of Cincinnati']::text[], '{}'::text[]),
  ('University of Colorado School of Medicine', NULL, 'md', 'US', 'Colorado', ARRAY['University of Colorado']::text[], ARRAY['cuanschutz.edu','ucdenver.edu']::text[]),
  ('University of Connecticut School of Medicine', NULL, 'md', 'US', 'Connecticut', ARRAY['University of Connecticut']::text[], '{}'::text[]),
  ('University of Florida College of Medicine', NULL, 'md', 'US', 'Florida', ARRAY['University of Florida']::text[], ARRAY['ufl.edu']::text[]),
  ('University of Hawaii, John A. Burns School of Medicine', NULL, 'md', 'US', 'Hawaii', ARRAY['University of Hawaii, John A. Burns','University of Hawaii John A. Burns School of Medicine']::text[], '{}'::text[]),
  ('University of Houston Tilman J. Fertitta Family College of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['University of Houston Tilman J. Fertitta Family']::text[], '{}'::text[]),
  ('University of Illinois College of Medicine', NULL, 'md', 'US', 'Illinois', ARRAY['University of Illinois']::text[], '{}'::text[]),
  ('University of Iowa Roy J. and Lucille A. Carver College of Medicine', NULL, 'md', 'US', 'Iowa', ARRAY['University of Iowa Roy J. and Lucille A. Carver']::text[], ARRAY['uiowa.edu']::text[]),
  ('University of Kansas School of Medicine', NULL, 'md', 'US', 'Kansas', ARRAY['University of Kansas']::text[], '{}'::text[]),
  ('University of Kentucky College of Medicine', NULL, 'md', 'US', 'Kentucky', ARRAY['University of Kentucky']::text[], '{}'::text[]),
  ('University of Louisville School of Medicine', NULL, 'md', 'US', 'Kentucky', ARRAY['University of Louisville']::text[], '{}'::text[]),
  ('University of Manitoba Max Rady College of Medicine', NULL, 'canada_md', 'CA', 'Manitoba', ARRAY['University of Manitoba Max Rady']::text[], '{}'::text[]),
  ('University of Maryland School of Medicine', NULL, 'md', 'US', 'Maryland', ARRAY['University of Maryland']::text[], '{}'::text[]),
  ('University of Massachusetts T.H. Chan School of Medicine', 'UMass', 'md', 'US', 'Massachusetts', ARRAY['UMass','UMass Chan','UMass Medical School','University of Massachusetts T.H. Chan','University of Massachusetts Medical School']::text[], ARRAY['umassmed.edu']::text[]),
  ('University of Medicine and Health Sciences', NULL, 'caribbean', 'KN', 'Saint Kitts and Nevis', '{}'::text[], '{}'::text[]),
  ('University of Miami Leonard M. Miller School of Medicine', NULL, 'md', 'US', 'Florida', ARRAY['University of Miami Leonard M. Miller']::text[], ARRAY['miami.edu','med.miami.edu']::text[]),
  ('University of Michigan Medical School', 'Michigan', 'md', 'US', 'Michigan', ARRAY['Michigan','University of Michigan']::text[], ARRAY['umich.edu','med.umich.edu']::text[]),
  ('University of Minnesota Medical School', NULL, 'md', 'US', 'Minnesota', ARRAY['University of Minnesota']::text[], ARRAY['umn.edu']::text[]),
  ('University of Mississippi School of Medicine', NULL, 'md', 'US', 'Mississippi', ARRAY['University of Mississippi']::text[], '{}'::text[]),
  ('University of Missouri-Columbia School of Medicine', NULL, 'md', 'US', 'Missouri', ARRAY['University of Missouri-Columbia']::text[], '{}'::text[]),
  ('University of Missouri–Kansas City School of Medicine', NULL, 'md', 'US', 'Missouri', ARRAY['University of Missouri–Kansas City']::text[], '{}'::text[]),
  ('University of Nebraska College of Medicine', NULL, 'md', 'US', 'Nebraska', ARRAY['University of Nebraska']::text[], '{}'::text[]),
  ('University of Nevada, Reno School of Medicine', NULL, 'md', 'US', 'Nevada', ARRAY['University of Nevada, Reno','University of Nevada Reno School of Medicine']::text[], '{}'::text[]),
  ('University of New England College of Osteopathic Medicine', NULL, 'do', 'US', 'Maine', ARRAY['University of New England']::text[], '{}'::text[]),
  ('University of New Mexico School of Medicine', NULL, 'md', 'US', 'New Mexico', ARRAY['University of New Mexico']::text[], ARRAY['unm.edu','salud.unm.edu']::text[]),
  ('University of North Carolina School of Medicine', NULL, 'md', 'US', 'North Carolina', ARRAY['University of North Carolina']::text[], ARRAY['unc.edu','med.unc.edu']::text[]),
  ('University of North Dakota School of Medicine and Health Sciences', NULL, 'md', 'US', 'North Dakota', ARRAY['University of North Dakota']::text[], '{}'::text[]),
  ('University of North Texas Health Science Center – Texas College of Osteopathic Medicine', NULL, 'do', 'US', 'Texas', ARRAY['University of North Texas Health Science Center – Texas']::text[], '{}'::text[]),
  ('University of Northern Colorado College of Osteopathic Medicine', NULL, 'do', 'US', 'Colorado', ARRAY['University of Northern Colorado']::text[], '{}'::text[]),
  ('University of Oklahoma College of Medicine', NULL, 'md', 'US', 'Oklahoma', ARRAY['University of Oklahoma']::text[], '{}'::text[]),
  ('University of Ottawa Faculty of Medicine', NULL, 'canada_md', 'CA', 'Ontario', ARRAY['University of Ottawa']::text[], '{}'::text[]),
  ('University of Pikeville – Kentucky College of Osteopathic Medicine', NULL, 'do', 'US', 'Kentucky', ARRAY['University of Pikeville – Kentucky']::text[], '{}'::text[]),
  ('University of Pittsburgh School of Medicine', NULL, 'md', 'US', 'Pennsylvania', ARRAY['University of Pittsburgh']::text[], ARRAY['pitt.edu']::text[]),
  ('University of Puerto Rico School of Medicine', NULL, 'md', 'US', 'Puerto Rico', ARRAY['University of Puerto Rico']::text[], '{}'::text[]),
  ('University of Rochester School of Medicine and Dentistry', NULL, 'md', 'US', 'New York', ARRAY['University of Rochester']::text[], '{}'::text[]),
  ('University of Saskatchewan College of Medicine', NULL, 'canada_md', 'CA', 'Saskatchewan', ARRAY['University of Saskatchewan']::text[], '{}'::text[]),
  ('University of South Carolina Kay and C. Edward Floyd, M.D. School of Medicine', NULL, 'md', 'US', 'South Carolina', ARRAY['University of South Carolina Kay and C. Edward Floyd, M.D.','University of South Carolina Kay and C. Edward Floyd M.D. School of Medicine']::text[], '{}'::text[]),
  ('University of South Carolina School of Medicine Greenville', NULL, 'md', 'US', 'South Carolina', '{}'::text[], '{}'::text[]),
  ('University of South Dakota Sanford School of Medicine', NULL, 'md', 'US', 'South Dakota', ARRAY['University of South Dakota Sanford']::text[], '{}'::text[]),
  ('University of Tennessee College of Medicine', NULL, 'md', 'US', 'Tennessee', ARRAY['University of Tennessee']::text[], '{}'::text[]),
  ('University of Texas Medical Branch John Sealy School of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['University of Texas Medical Branch John Sealy']::text[], '{}'::text[]),
  ('University of Texas Rio Grande Valley School of Medicine', NULL, 'md', 'US', 'Texas', ARRAY['University of Texas Rio Grande Valley']::text[], '{}'::text[]),
  ('University of Texas Southwestern Medical School', 'UT Southwestern', 'md', 'US', 'Texas', ARRAY['UTSW','UT Southwestern','UT Southwestern Medical School','University of Texas Southwestern']::text[], ARRAY['utsouthwestern.edu']::text[]),
  ('University of the Incarnate Word School of Osteopathic Medicine', NULL, 'do', 'US', 'Texas', ARRAY['University of the Incarnate Word']::text[], '{}'::text[]),
  ('University of Toledo College of Medicine and Life Sciences', NULL, 'md', 'US', 'Ohio', ARRAY['University of Toledo']::text[], '{}'::text[]),
  ('University of Toronto Temerty Faculty of Medicine', NULL, 'canada_md', 'CA', 'Ontario', ARRAY['U of T Medicine','Temerty Medicine','University of Toronto Temerty','University of Toronto Faculty of Medicine']::text[], ARRAY['utoronto.ca']::text[]),
  ('University of Virginia School of Medicine', NULL, 'md', 'US', 'Virginia', ARRAY['University of Virginia']::text[], ARRAY['virginia.edu']::text[]),
  ('University of Washington School of Medicine', NULL, 'md', 'US', 'Washington', ARRAY['University of Washington']::text[], ARRAY['uw.edu','washington.edu']::text[]),
  ('University of Wisconsin School of Medicine and Public Health', NULL, 'md', 'US', 'Wisconsin', ARRAY['University of Wisconsin']::text[], ARRAY['wisc.edu']::text[]),
  ('Université de Montréal Faculté de médecine', NULL, 'canada_md', 'CA', 'Quebec', ARRAY['Université de Montréal']::text[], '{}'::text[]),
  ('Université de Sherbrooke Faculté de médecine et des sciences de la santé', NULL, 'canada_md', 'CA', 'Quebec', ARRAY['Université de Sherbrooke']::text[], '{}'::text[]),
  ('Université Laval Faculté de médecine', NULL, 'canada_md', 'CA', 'Quebec', ARRAY['Université Laval']::text[], '{}'::text[]),
  ('USF Health Morsani College of Medicine', NULL, 'md', 'US', 'Florida', ARRAY['USF Health Morsani']::text[], ARRAY['usf.edu']::text[]),
  ('Vanderbilt University School of Medicine', 'Vanderbilt', 'md', 'US', 'Tennessee', ARRAY['Vanderbilt','Vanderbilt University']::text[], ARRAY['vanderbilt.edu','vumc.org']::text[]),
  ('Virginia Commonwealth University School of Medicine', NULL, 'md', 'US', 'Virginia', ARRAY['Virginia Commonwealth University']::text[], ARRAY['vcu.edu']::text[]),
  ('Virginia Tech Carilion School of Medicine', NULL, 'md', 'US', 'Virginia', ARRAY['Virginia Tech Carilion']::text[], '{}'::text[]),
  ('Wake Forest School of Medicine', NULL, 'md', 'US', 'North Carolina', '{}'::text[], ARRAY['wakehealth.edu']::text[]),
  ('Washington State University Elson S. Floyd College of Medicine', NULL, 'md', 'US', 'Washington', ARRAY['Washington State University Elson S. Floyd']::text[], '{}'::text[]),
  ('Washington University in St. Louis School of Medicine', 'WashU', 'md', 'US', 'Missouri', ARRAY['WUSM','WashU','Washington University in St. Louis','Washington University School of Medicine']::text[], ARRAY['wustl.edu']::text[]),
  ('Wayne State University School of Medicine', NULL, 'md', 'US', 'Michigan', ARRAY['Wayne State University']::text[], '{}'::text[]),
  ('Weill Cornell Medical College', 'Weill Cornell', 'md', 'US', 'New York', ARRAY['Weill Cornell','Cornell Medical School','Weill Cornell Medicine']::text[], ARRAY['med.cornell.edu','cornell.edu']::text[]),
  ('West Virginia School of Osteopathic Medicine', NULL, 'do', 'US', 'West Virginia', ARRAY['West Virginia']::text[], '{}'::text[]),
  ('West Virginia University School of Medicine', NULL, 'md', 'US', 'West Virginia', ARRAY['West Virginia University']::text[], '{}'::text[]),
  ('Western Michigan University Homer Stryker M.D. School of Medicine', NULL, 'md', 'US', 'Michigan', ARRAY['Western Michigan University Homer Stryker M.D.']::text[], '{}'::text[]),
  ('Western University of Health Sciences College of Osteopathic Medicine of the Pacific', NULL, 'do', 'US', 'California', ARRAY['COMP','WesternU COMP','COMP-Northwest','Western University COMP','Western University of Health Sciences','Western University of Health Sciences College of Osteopathic Medicine of the Pacific-Northwest']::text[], '{}'::text[]),
  ('Western University Schulich School of Medicine & Dentistry', NULL, 'canada_md', 'CA', 'Ontario', ARRAY['Western University']::text[], '{}'::text[]),
  ('William Carey University College of Osteopathic Medicine', NULL, 'do', 'US', 'Mississippi', ARRAY['William Carey University']::text[], '{}'::text[]),
  ('Xavier University College of Osteopathic Medicine', NULL, 'do', 'US', 'Ohio', ARRAY['Xavier University']::text[], '{}'::text[]),
  ('Xavier University School of Medicine', NULL, 'caribbean', 'AW', 'Aruba', ARRAY['Xavier University']::text[], '{}'::text[]),
  ('Yale Physician Associate Program', 'Yale PA', 'allied', 'US', 'Connecticut', ARRAY['Yale PA','Yale PA Program','Yale Physician Assistant Program']::text[], ARRAY['yale.edu']::text[]),
  ('Yale School of Medicine', 'Yale', 'md', 'US', 'Connecticut', ARRAY['YSM','Yale','Yale Med','Yale SOM','Yale University','Yale Medical School','Yale University School of Medicine']::text[], ARRAY['yale.edu']::text[]),
  ('Yale School of Nursing', 'Yale Nursing', 'allied', 'US', 'Connecticut', ARRAY['YSN','Yale Nursing']::text[], ARRAY['yale.edu']::text[]),
  ('Yale School of Public Health', 'YSPH', 'allied', 'US', 'Connecticut', ARRAY['YSPH']::text[], ARRAY['yale.edu']::text[])
ON CONFLICT (canonical_name) DO UPDATE SET
  short_name    = EXCLUDED.short_name,
  kind          = EXCLUDED.kind,
  country       = EXCLUDED.country,
  region        = EXCLUDED.region,
  aliases       = EXCLUDED.aliases,
  email_domains = EXCLUDED.email_domains;
